# Generated by Django 2.2.6 on 2020-05-27 15:27

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
