# Generated by Django 2.2.6 on 2020-05-28 03:15

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerProStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
            ],
            options={
                'verbose_name': '特训状态',
                'verbose_name_plural': '特训状态',
            },
        ),
        migrations.CreateModel(
            name='ExerProPotionEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (300, '抽取卡牌'), (310, '移除卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProPotion', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特训药水使用效果',
                'verbose_name_plural': '特训药水使用效果',
            },
        ),
        migrations.CreateModel(
            name='ExerProItemEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (300, '抽取卡牌'), (310, '移除卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特训物品使用效果',
                'verbose_name_plural': '特训物品使用效果',
            },
        ),
        migrations.CreateModel(
            name='ExerProCardEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (300, '抽取卡牌'), (310, '移除卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProCard', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特训卡片使用效果',
                'verbose_name_plural': '特训卡片使用效果',
            },
        ),
    ]
