# Generated by Django 2.2.6 on 2020-08-22 00:08

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.cache_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_module', '0002_auto_20200822_0008'),
        ('player_module', '0002_auto_20200822_0008'),
        ('english_pro_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_word', models.CharField(max_length=32, verbose_name='卡牌词')),
                ('enemy_word', models.CharField(max_length=32, verbose_name='敌人词')),
                ('hurt_rate', models.SmallIntegerField(default=100, verbose_name='伤害比率')),
            ],
            options={
                'verbose_name': '反义词',
                'verbose_name_plural': '反义词',
            },
        ),
        migrations.CreateModel(
            name='ExerProCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('icon_index', models.PositiveSmallIntegerField(default=0, verbose_name='图标索引')),
                ('start_ani_index', models.PositiveSmallIntegerField(default=0, verbose_name='起手动画索引')),
                ('target_ani_index', models.PositiveSmallIntegerField(default=0, verbose_name='目标动画索引')),
                ('cost', models.PositiveSmallIntegerField(default=1, verbose_name='消耗能量')),
                ('card_type', models.PositiveSmallIntegerField(choices=[(1, '攻击'), (2, '技能'), (3, '能力'), (4, '诅咒')], default=1, verbose_name='卡片类型')),
                ('skin_index', models.PositiveSmallIntegerField(default=0, verbose_name='卡牌皮肤索引')),
                ('inherent', models.BooleanField(default=False, verbose_name='固有')),
                ('disposable', models.BooleanField(default=False, verbose_name='消耗')),
                ('boughtable', models.BooleanField(default=True, verbose_name='可否购买')),
                ('character', models.CharField(blank=True, default='', max_length=32, verbose_name='性质')),
                ('target', models.PositiveSmallIntegerField(choices=[(0, '默认'), (1, '单体'), (2, '群体')], default=0, verbose_name='目标')),
            ],
            options={
                'verbose_name': '特训物品',
                'verbose_name_plural': '特训物品',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerProEnemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '普通'), (2, '精英'), (3, 'BOSS')], default=1, verbose_name='等级')),
                ('mhp', models.PositiveSmallIntegerField(default=100, verbose_name='最大体力值')),
                ('power', models.PositiveSmallIntegerField(default=10, verbose_name='力量')),
                ('defense', models.PositiveSmallIntegerField(default=10, verbose_name='格挡')),
                ('character', models.CharField(blank=True, default='', max_length=32, verbose_name='性格')),
            ],
            options={
                'verbose_name': '基础物品',
                'verbose_name_plural': '基础物品',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerProItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('icon_index', models.PositiveSmallIntegerField(default=0, verbose_name='图标索引')),
                ('start_ani_index', models.PositiveSmallIntegerField(default=0, verbose_name='起手动画索引')),
                ('target_ani_index', models.PositiveSmallIntegerField(default=0, verbose_name='目标动画索引')),
            ],
            options={
                'verbose_name': '特训物品',
                'verbose_name_plural': '特训物品',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerProItemStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='星级颜色')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '特训物品星级',
                'verbose_name_plural': '特训物品星级',
            },
        ),
        migrations.CreateModel(
            name='ExerProMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='地图名称')),
                ('description', models.CharField(max_length=512, verbose_name='故事描述')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='地图难度')),
                ('min_level', models.PositiveSmallIntegerField(default=1, verbose_name='等级要求')),
            ],
            options={
                'verbose_name': '特训地图',
                'verbose_name_plural': '特训地图',
            },
        ),
        migrations.CreateModel(
            name='ExerProMapStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='序号')),
                ('max_battle_enemies', models.PositiveSmallIntegerField(default=1, verbose_name='战斗最大敌人数量')),
                ('steps', jsonfield.fields.JSONField(default=[3, 4, 5, 2, 1], verbose_name='每步据点个数')),
                ('max_fork_node', models.PositiveSmallIntegerField(default=5, verbose_name='最大分叉据点数量')),
                ('max_fork', models.PositiveSmallIntegerField(default=3, verbose_name='最大分叉选择数')),
                ('node_rate', jsonfield.fields.JSONField(default=[1, 1, 1, 1, 1, 1], verbose_name='据点比例')),
                ('enemies', models.ManyToManyField(to='english_pro_module.ExerProEnemy', verbose_name='敌人集合')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProMap', verbose_name='地图')),
            ],
            options={
                'verbose_name': '地图关卡',
                'verbose_name_plural': '地图关卡',
            },
        ),
        migrations.CreateModel(
            name='ExerProPotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('icon_index', models.PositiveSmallIntegerField(default=0, verbose_name='图标索引')),
                ('start_ani_index', models.PositiveSmallIntegerField(default=0, verbose_name='起手动画索引')),
                ('target_ani_index', models.PositiveSmallIntegerField(default=0, verbose_name='目标动画索引')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItemStar', verbose_name='星级')),
            ],
            options={
                'verbose_name': '特训物品',
                'verbose_name_plural': '特训物品',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerProState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('icon_index', models.PositiveSmallIntegerField(default=0, verbose_name='图标索引')),
                ('max_turns', models.PositiveSmallIntegerField(default=0, verbose_name='最大状态回合数')),
                ('is_nega', models.BooleanField(default=False, verbose_name='是否负面状态')),
            ],
            options={
                'verbose_name': '基础物品',
                'verbose_name_plural': '基础物品',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('ques_types', models.CharField(max_length=32, verbose_name='题型')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '据点类型',
                'verbose_name_plural': '据点类型',
            },
        ),
        migrations.CreateModel(
            name='FirstCardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('cards', jsonfield.fields.JSONField(default=[], verbose_name='卡组ID集')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '初始卡组',
                'verbose_name_plural': '初始卡组',
            },
        ),
        migrations.CreateModel(
            name='ExerProStateTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '攻击伤害加成'), (2, '受到伤害加成'), (3, '回复加成'), (4, '回复加成（休息据点）'), (5, '回合结束HP回复'), (6, '回合开始HP回复'), (7, '战斗结束HP回复'), (8, '战斗开始HP回复'), (9, '属性加成值'), (10, '回合属性加成值'), (11, '战斗属性加成值'), (12, '回合开始抽牌数加成'), (13, '战斗开始抽牌数加成')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProState', verbose_name='状态')),
            ],
            options={
                'verbose_name': '特训状态特性',
                'verbose_name_plural': '特训状态特性',
            },
        ),
        migrations.CreateModel(
            name='ExerProRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False, verbose_name='开始标志')),
                ('generated', models.BooleanField(default=False, verbose_name='生成标志')),
                ('cur_index', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='当前据点索引')),
                ('node_flag', models.BooleanField(default=False, verbose_name='是否完成据点事件')),
                ('word_level', models.PositiveSmallIntegerField(default=1, verbose_name='单词等级')),
                ('gold', models.PositiveSmallIntegerField(default=100, verbose_name='金币')),
                ('nodes', jsonfield.fields.JSONField(blank=True, default=None, null=True, verbose_name='据点数据')),
                ('actor', jsonfield.fields.JSONField(blank=True, default=None, null=True, verbose_name='角色数据')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProMapStage', verbose_name='关卡')),
            ],
            options={
                'verbose_name': '特训记录',
                'verbose_name_plural': '特训记录',
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='ExerProPotionEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (230, '回复能量'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币'), (510, '获得卡牌'), (511, '失去卡牌'), (512, '复制卡牌'), (520, '获得道具'), (521, '失去道具'), (530, '获得药水'), (531, '失去药水')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProPotion', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特训药水使用效果',
                'verbose_name_plural': '特训药水使用效果',
            },
        ),
        migrations.CreateModel(
            name='ExerProItemTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '攻击伤害加成'), (2, '受到伤害加成'), (3, '回复加成'), (4, '回复加成（休息据点）'), (5, '回合结束HP回复'), (6, '回合开始HP回复'), (7, '战斗结束HP回复'), (8, '战斗开始HP回复'), (9, '属性加成值'), (10, '回合属性加成值'), (11, '战斗属性加成值'), (12, '回合开始抽牌数加成'), (13, '战斗开始抽牌数加成')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特训物品特性',
                'verbose_name_plural': '特训物品特性',
            },
        ),
        migrations.AddField(
            model_name='exerproitem',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItemStar', verbose_name='星级'),
        ),
        migrations.CreateModel(
            name='ExerProCardEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (230, '回复能量'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币'), (510, '获得卡牌'), (511, '失去卡牌'), (512, '复制卡牌'), (520, '获得道具'), (521, '失去道具'), (530, '获得药水'), (531, '失去药水')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProCard', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特训卡片使用效果',
                'verbose_name_plural': '特训卡片使用效果',
            },
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItemStar', verbose_name='星级'),
        ),
        migrations.CreateModel(
            name='EnemyEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (230, '回复能量'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币'), (510, '获得卡牌'), (511, '失去卡牌'), (512, '复制卡牌'), (520, '获得道具'), (521, '失去道具'), (530, '获得药水'), (531, '失去药水')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProEnemy', verbose_name='敌人')),
            ],
            options={
                'verbose_name': '特训敌人攻击效果',
                'verbose_name_plural': '特训敌人攻击效果',
            },
        ),
        migrations.CreateModel(
            name='EnemyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', jsonfield.fields.JSONField(default=[], verbose_name='回合')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '攻击'), (2, '属性提升'), (3, '状态提升'), (4, '属性削弱'), (5, '状态削弱'), (6, '逃跑'), (7, '无')], default=7, verbose_name='类型')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='参数')),
                ('rate', models.PositiveSmallIntegerField(default=10, verbose_name='权重')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProEnemy', verbose_name='敌人')),
            ],
            options={
                'verbose_name': '敌人行动',
                'verbose_name_plural': '敌人行动',
            },
        ),
    ]
