# Generated by Django 2.2.6 on 2020-05-29 18:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0003_auto_20200226_1009'),
        ('english_pro_module', '0002_exerprocardeffect_exerproitemeffect_exerpropotioneffect_exerprostatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfinitiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, verbose_name='单词')),
                ('chinese', models.CharField(max_length=64, verbose_name='中文')),
                ('infinitive', models.CharField(max_length=64, verbose_name='不定式项')),
            ],
            options={
                'verbose_name': '不定式题',
                'verbose_name_plural': '不定式题',
            },
        ),
        migrations.RenameField(
            model_name='exerproenemy',
            old_name='level',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='exerpropotion',
            name='hp_rate',
        ),
        migrations.RemoveField(
            model_name='exerpropotion',
            name='hp_recover',
        ),
        migrations.RemoveField(
            model_name='exerpropotion',
            name='power_add',
        ),
        migrations.RemoveField(
            model_name='exerpropotion',
            name='power_rate',
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='character',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='性质'),
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='disposable',
            field=models.BooleanField(default=False, verbose_name='消耗'),
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='inherent',
            field=models.BooleanField(default=False, verbose_name='固有'),
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, '攻击'), (2, '技能'), (3, '能力'), (4, '诅咒')], default=0, verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='exerproenemy',
            name='character',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='性格'),
        ),
        migrations.AddField(
            model_name='exerproenemy',
            name='defense',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='格挡'),
        ),
        migrations.AddField(
            model_name='exerproitem',
            name='gold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='金币'),
        ),
        migrations.AddField(
            model_name='exerpropotion',
            name='gold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='金币'),
        ),
        migrations.AlterField(
            model_name='exerprocard',
            name='card_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '攻击'), (2, '技能'), (3, '能力'), (4, '诅咒')], default=1, verbose_name='卡片类型'),
        ),
        migrations.CreateModel(
            name='ExerProItemStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='星级颜色')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '特训物品星级',
                'verbose_name_plural': '特训物品星级',
            },
        ),
        migrations.CreateModel(
            name='EnemyEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (300, '抽取卡牌'), (310, '移除卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProEnemy', verbose_name='敌人')),
            ],
            options={
                'verbose_name': '特训敌人攻击效果',
                'verbose_name_plural': '特训敌人攻击效果',
            },
        ),
        migrations.CreateModel(
            name='EnemyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', jsonfield.fields.JSONField(default=[], verbose_name='回合')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '攻击'), (2, '提升'), (3, '削弱'), (4, '逃跑'), (5, '无')], default=5, verbose_name='类型')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='参数')),
                ('rate', models.PositiveSmallIntegerField(default=10, verbose_name='权重')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProEnemy', verbose_name='敌人')),
            ],
            options={
                'verbose_name': '敌人行动',
                'verbose_name_plural': '敌人行动',
            },
        ),
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('card_word', models.CharField(max_length=32, verbose_name='卡牌词')),
                ('enemy_word', models.CharField(max_length=32, verbose_name='敌人词')),
                ('hurt_rate', models.SmallIntegerField(default=100, verbose_name='伤害比率')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '反义词',
                'verbose_name_plural': '反义词',
            },
        ),
        migrations.AddField(
            model_name='exerproitem',
            name='star',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItemStar', verbose_name='星级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerpropotion',
            name='star',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItemStar', verbose_name='星级'),
            preserve_default=False,
        ),
    ]
