# Generated by Django 2.2.7 on 2020-06-01 02:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0014_auto_20200510_1947'),
        ('english_pro_module', '0003_auto_20200529_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordrecord',
            name='current',
            field=models.BooleanField(default=False, verbose_name='是否是当前轮'),
        ),
        migrations.AddField(
            model_name='wordrecord',
            name='current_correct',
            field=models.BooleanField(default=False, null=True, verbose_name='当前轮是否答对'),
        ),
        migrations.CreateModel(
            name='ExerProRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WordLevel', models.PositiveSmallIntegerField(default=0, verbose_name='单词等级')),
                ('words', jsonfield.fields.JSONField(default=[], verbose_name='单词ID集')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '单词轮数',
                'verbose_name_plural': '单词轮数',
            },
        ),
    ]
