# Generated by Django 2.2.6 on 2020-06-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0003_auto_20200226_1009'),
        ('english_pro_module', '0003_auto_20200529_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerprocard',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, '默认'), (1, '单体'), (2, '群体')], default=0, verbose_name='目标'),
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('ques_types', models.CharField(max_length=32, verbose_name='题型')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '据点类型词',
                'verbose_name_plural': '据点类型词',
            },
        ),
    ]
