# Generated by Django 2.2.6 on 2020-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0005_auto_20200601_0301'),
        ('english_pro_module', '0004_auto_20200601_1905'),
    ]

    operations = [
    ]
