# Generated by Django 2.2.7 on 2020-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0006_auto_20200602_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='chinese',
            field=models.CharField(max_length=128, verbose_name='中文'),
        ),
    ]
