# Generated by Django 2.2.6 on 2020-06-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0007_auto_20200602_1425'),
        ('english_pro_module', '0007_auto_20200602_1740'),
    ]

    operations = [
    ]
