# Generated by Django 2.2.6 on 2020-06-03 17:06

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0009_auto_20200602_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfinitiveQuestion',
            new_name='PhraseQuestion',
        ),
        migrations.RenameField(
            model_name='phrasequestion',
            old_name='infinitive',
            new_name='phrase',
        ),
        migrations.AddField(
            model_name='exerprorecord',
            name='actor',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True, verbose_name='角色数据'),
        ),
        migrations.AddField(
            model_name='exerprorecord',
            name='cur_index',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='当前据点索引'),
        ),
        migrations.AddField(
            model_name='exerprorecord',
            name='generated',
            field=models.BooleanField(default=False, verbose_name='生成标志'),
        ),
        migrations.AddField(
            model_name='exerprorecord',
            name='nodes',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True, verbose_name='据点数据'),
        ),
        migrations.AddField(
            model_name='exerprorecord',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProMapStage', verbose_name='关卡'),
        ),
        migrations.AddField(
            model_name='exerprorecord',
            name='started',
            field=models.BooleanField(default=False, verbose_name='开始标志'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=64, unique=True, verbose_name='英文'),
        ),
    ]
