# Generated by Django 2.2.6 on 2020-06-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0010_auto_20200603_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerpropotion',
            options={'verbose_name': '特训药水', 'verbose_name_plural': '特训药水'},
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='gold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='金币'),
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItemStar', verbose_name='星级'),
            preserve_default=False,
        ),
    ]
