# Generated by Django 2.2.6 on 2020-06-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0011_auto_20200604_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerProState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('max_turns', models.PositiveSmallIntegerField(default=0, verbose_name='最大状态回合数')),
                ('is_nega', models.BooleanField(default=False, verbose_name='是否负面状态')),
            ],
            options={
                'verbose_name': '特训状态',
                'verbose_name_plural': '特训状态',
            },
        ),
        migrations.DeleteModel(
            name='ExerProStatus',
        ),
        migrations.RenameField(
            model_name='enemyaction',
            old_name='round',
            new_name='rounds',
        ),
        migrations.AddField(
            model_name='exerprorecord',
            name='node_flag',
            field=models.BooleanField(default=False, verbose_name='是否完成据点事件'),
        ),
        migrations.AlterField(
            model_name='enemyaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '攻击'), (2, '提升'), (3, '削弱'), (4, '状态'), (5, '逃跑'), (6, '无')], default=6, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='enemyeffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
        migrations.AlterField(
            model_name='exerprocardeffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
        migrations.AlterField(
            model_name='exerproitemeffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
        migrations.AlterField(
            model_name='exerpropotioneffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '残虐天性'), (600, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
    ]
