# Generated by Django 2.2.6 on 2020-06-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0012_auto_20200609_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='times',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='重复次数'),
        ),
    ]
