# Generated by Django 2.2.6 on 2020-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0013_listeningquestion_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerprocard',
            name='icon_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='图标索引'),
        ),
        migrations.AddField(
            model_name='exerproitem',
            name='icon_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='图标索引'),
        ),
        migrations.AddField(
            model_name='exerpropotion',
            name='icon_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='图标索引'),
        ),
        migrations.AlterField(
            model_name='enemyaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '攻击'), (2, '属性提升'), (3, '状态提升'), (4, '属性削弱'), (5, '状态削弱'), (6, '逃跑'), (7, '无')], default=7, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='enemyeffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币'), (600, '残虐天性'), (700, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
        migrations.AlterField(
            model_name='exerprocardeffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币'), (600, '残虐天性'), (700, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
        migrations.AlterField(
            model_name='exerproitemeffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币'), (600, '残虐天性'), (700, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
        migrations.AlterField(
            model_name='exerpropotioneffect',
            name='code',
            field=models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币'), (600, '残虐天性'), (700, '增加己方状态')], default=0, verbose_name='效果编号'),
        ),
    ]
