# Generated by Django 2.2.6 on 2020-06-19 09:19

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0004_gametip'),
        ('english_pro_module', '0015_auto_20200616_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerprocard',
            name='skin_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='卡牌皮肤索引'),
        ),
        migrations.CreateModel(
            name='FirstCardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('cards', jsonfield.fields.JSONField(default=[], verbose_name='卡组ID集')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '初始卡组',
                'verbose_name_plural': '初始卡组',
            },
        ),
    ]
