# Generated by Django 2.2.6 on 2020-06-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0016_auto_20200619_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerprocard',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='exerproitem',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='exerpropotion',
            name='gold',
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='start_ani_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='起手动画索引'),
        ),
        migrations.AddField(
            model_name='exerprocard',
            name='target_ani_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='目标动画索引'),
        ),
        migrations.AddField(
            model_name='exerproitem',
            name='start_ani_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='起手动画索引'),
        ),
        migrations.AddField(
            model_name='exerproitem',
            name='target_ani_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='目标动画索引'),
        ),
        migrations.AddField(
            model_name='exerpropotion',
            name='start_ani_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='起手动画索引'),
        ),
        migrations.AddField(
            model_name='exerpropotion',
            name='target_ani_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='目标动画索引'),
        ),
    ]
