# Generated by Django 2.2.6 on 2020-06-23 01:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0017_auto_20200622_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerProItemTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (230, '回复能量'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特训物品特性',
                'verbose_name_plural': '特训物品特性',
            },
        ),
        migrations.CreateModel(
            name='ExerProStateTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (230, '回复能量'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.ExerProState', verbose_name='状态')),
            ],
            options={
                'verbose_name': '特训状态特性',
                'verbose_name_plural': '特训状态特性',
            },
        ),
        migrations.DeleteModel(
            name='ExerProItemEffect',
        ),
    ]
