# Generated by Django 2.2.6 on 2020-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0018_auto_20200623_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerprostate',
            name='icon_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='图标索引'),
        ),
    ]
