# Generated by Django 2.2.6 on 2020-06-23 11:35

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0019_exerprostate_icon_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='题干')),
                ('description', models.TextField(blank=True, null=True, verbose_name='题解')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '判断题'), (-1, '其他题')], default=0, verbose_name='类型')),
                ('for_test', models.BooleanField(default=False, verbose_name='测试')),
                ('event_name', models.CharField(max_length=64, verbose_name='剧情事件名称')),
                ('picture', models.ImageField(upload_to=utils.model_utils.PlotQuestionImageUpload(), verbose_name='剧情图标')),
            ],
            options={
                'verbose_name': '剧情题目',
                'verbose_name_plural': '剧情题目',
            },
        ),
        migrations.CreateModel(
            name='PlotQuesChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='编号')),
                ('text', models.TextField(verbose_name='文本')),
                ('answer', models.BooleanField(default=False, verbose_name='正误')),
                ('result_text', models.TextField(verbose_name='选项对应的结果文本')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.PlotQuestion', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '剧情题目选项',
                'verbose_name_plural': '剧情题目选项',
            },
        ),
        migrations.CreateModel(
            name='ExerProPlotEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (1, '造成伤害'), (2, '造成伤害（完美斩击）'), (3, '造成伤害（黑旋风）'), (4, '造成伤害（波动拳）'), (5, '造成伤害（仪式匕首）'), (100, '回复体力值'), (200, '增加能力值'), (201, '获得MHP'), (202, '获得力量'), (203, '获得格挡'), (204, '获得敏捷'), (205, '增加能力值（紧急按钮）'), (210, '临时增加能力值'), (211, '临时获得MHP'), (212, '临时获得力量'), (213, '临时获得格挡'), (214, '临时获得敏捷'), (220, '增加状态'), (221, '移除状态'), (222, '移除消极状态'), (230, '回复能量'), (300, '抽取卡牌'), (310, '消耗卡牌'), (400, '更改耗能'), (401, '更改耗能（发现）'), (402, '更改耗能（疯狂）'), (500, '获得金币')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('effects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.PlotQuesChoice', verbose_name='效果')),
            ],
            options={
                'verbose_name': '剧情题目效果',
                'verbose_name_plural': '剧情题目效果',
            },
        ),
    ]
