# Generated by Django 2.2.6 on 2020-06-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0020_exerproploteffect_plotqueschoice_plotquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerprorecord',
            name='gold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='金币'),
        ),
    ]
