# Generated by Django 2.2.6 on 2020-06-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0021_exerprorecord_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerprorecord',
            name='gold',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='金币'),
        ),
    ]
