# Generated by Django 2.2.6 on 2020-06-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0022_auto_20200624_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerproploteffect',
            name='effects',
        ),
        migrations.AddField(
            model_name='exerproploteffect',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='english_pro_module.PlotQuesChoice', verbose_name='选项'),
            preserve_default=False,
        ),
    ]
