# Generated by Django 2.2.6 on 2020-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0024_auto_20200627_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotqueschoice',
            name='gold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='所需金币'),
        ),
    ]
