# Generated by Django 2.2.6 on 2020-07-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_pro_module', '0026_auto_20200716_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerprocard',
            options={'verbose_name': '特训物品', 'verbose_name_plural': '特训物品'},
        ),
        migrations.AlterModelOptions(
            name='exerproenemy',
            options={'verbose_name': '基础物品', 'verbose_name_plural': '基础物品'},
        ),
        migrations.AlterModelOptions(
            name='exerpropotion',
            options={'verbose_name': '特训物品', 'verbose_name_plural': '特训物品'},
        ),
        migrations.AlterModelOptions(
            name='exerprostate',
            options={'verbose_name': '基础物品', 'verbose_name_plural': '基础物品'},
        ),
    ]
