# Generated by Django 2.2.6 on 2019-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='显示名称')),
                ('attr', models.CharField(max_length=8, verbose_name='程序属性名')),
                ('description', models.CharField(max_length=64, verbose_name='描述')),
            ],
            options={
                'verbose_name': '基本属性',
                'verbose_name_plural': '基本属性',
            },
        ),
        migrations.CreateModel(
            name='GameTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='艾瑟萌学院', max_length=12, verbose_name='游戏名')),
                ('eng_name', models.CharField(default='Exermon', max_length=24, verbose_name='游戏名（英文）')),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_version', models.CharField(max_length=16, unique=True, verbose_name='版本号')),
                ('sub_version', models.CharField(max_length=16, unique=True, verbose_name='版本号')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('update_note', models.TextField(blank=True, default='', verbose_name='更新日志')),
                ('description', models.CharField(blank=True, default='', max_length=64, verbose_name='附加描述')),
                ('is_used', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '游戏配置数据',
                'verbose_name_plural': '游戏配置数据',
            },
        ),
    ]
