# Generated by Django 2.2.6 on 2020-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='显示名称')),
                ('attr', models.CharField(max_length=8, verbose_name='程序属性名')),
                ('max_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大值')),
                ('min_value', models.PositiveSmallIntegerField(default=0, verbose_name='最小值')),
                ('default', models.PositiveSmallIntegerField(default=0, verbose_name='最小值')),
                ('scale', models.PositiveSmallIntegerField(default=1, verbose_name='属性比例值')),
                ('description', models.CharField(max_length=64, verbose_name='描述')),
            ],
            options={
                'verbose_name': '基本属性',
                'verbose_name_plural': '基本属性',
            },
        ),
        migrations.CreateModel(
            name='ExerEquipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(max_length=64, verbose_name='描述')),
            ],
            options={
                'verbose_name': '艾瑟萌装备类型',
                'verbose_name_plural': '艾瑟萌装备类型',
            },
        ),
        migrations.CreateModel(
            name='GameTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='艾瑟萌学院', max_length=12, verbose_name='游戏名')),
                ('eng_name', models.CharField(default='Exermon', max_length=24, verbose_name='游戏名（英文）')),
                ('gold', models.CharField(default='金币', max_length=6, verbose_name='金币')),
                ('ticket', models.CharField(default='点券', max_length=6, verbose_name='点券')),
                ('bound_ticket', models.CharField(default='绑定点券', max_length=6, verbose_name='绑定点券')),
                ('activated', models.BooleanField(default=True, verbose_name='激活')),
            ],
            options={
                'verbose_name': '游戏用语',
                'verbose_name_plural': '游戏用语',
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_version', models.CharField(max_length=16, unique=True, verbose_name='版本号')),
                ('sub_version', models.CharField(max_length=16, unique=True, verbose_name='版本号')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('update_note', models.TextField(blank=True, default='', verbose_name='更新日志')),
                ('description', models.CharField(blank=True, default='', max_length=64, verbose_name='附加描述')),
                ('is_used', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '游戏版本',
                'verbose_name_plural': '游戏版本',
            },
        ),
        migrations.CreateModel(
            name='HumanEquipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(max_length=64, verbose_name='描述')),
            ],
            options={
                'verbose_name': '人类装备类型',
                'verbose_name_plural': '人类装备类型',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='名称')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='分值')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='UsableItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(max_length=64, verbose_name='描述')),
            ],
            options={
                'verbose_name': '可用物品类型',
                'verbose_name_plural': '可用物品类型',
            },
        ),
    ]
