# Generated by Django 2.2.6 on 2020-02-18 00:05

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='属性颜色')),
                ('attr', models.CharField(max_length=8, verbose_name='程序属性名')),
                ('max_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大值')),
                ('min_value', models.PositiveSmallIntegerField(default=0, verbose_name='最小值')),
                ('default', models.PositiveSmallIntegerField(default=0, verbose_name='默认值')),
                ('scale', models.PositiveSmallIntegerField(default=1, verbose_name='属性比例值')),
            ],
            options={
                'verbose_name': '基本属性',
                'verbose_name_plural': '基本属性',
            },
        ),
        migrations.CreateModel(
            name='GameConfigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='艾瑟萌学院', max_length=12, verbose_name='游戏名')),
                ('eng_name', models.CharField(default='Exermon', max_length=24, verbose_name='游戏名（英文）')),
                ('gold', models.CharField(default='金币', max_length=6, verbose_name='金币')),
                ('ticket', models.CharField(default='点券', max_length=6, verbose_name='点券')),
                ('bound_ticket', models.CharField(default='绑定点券', max_length=6, verbose_name='绑定点券')),
            ],
            options={
                'verbose_name': '游戏配置',
                'verbose_name_plural': '游戏配置',
            },
        ),
        migrations.CreateModel(
            name='UsableItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '可用物品类型',
                'verbose_name_plural': '可用物品类型',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='科目颜色')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='分值')),
                ('force', models.BooleanField(default=False, verbose_name='必选科目')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='QuestionStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='星级颜色')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='等级要求')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='等级权重')),
                ('exp_incr', models.PositiveSmallIntegerField(default=0, verbose_name='基础经验奖励')),
                ('gold_incr', models.PositiveSmallIntegerField(default=0, verbose_name='基础金币奖励')),
                ('std_time', models.PositiveSmallIntegerField(default=0, verbose_name='标准时间（分）')),
                ('min_time', models.PositiveSmallIntegerField(default=0, verbose_name='最短时间（秒）')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '题目星级',
                'verbose_name_plural': '题目星级',
            },
        ),
        migrations.CreateModel(
            name='ItemStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='星级颜色')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '物品星级',
                'verbose_name_plural': '物品星级',
            },
        ),
        migrations.CreateModel(
            name='HumanEquipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '人类装备类型',
                'verbose_name_plural': '人类装备类型',
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_version', models.CharField(max_length=16, verbose_name='主版本号')),
                ('sub_version', models.CharField(max_length=16, unique=True, verbose_name='副版本号')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('update_note', models.TextField(blank=True, default='', verbose_name='更新日志')),
                ('description', models.CharField(blank=True, default='', max_length=64, verbose_name='附加描述')),
                ('is_used', models.BooleanField(default=True, verbose_name='启用')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='游戏配置')),
            ],
            options={
                'verbose_name': '游戏版本',
                'verbose_name_plural': '游戏版本',
            },
        ),
        migrations.CreateModel(
            name='ExerStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='星级颜色')),
                ('max_level', models.PositiveSmallIntegerField(default=0, verbose_name='最大等级')),
                ('level_exp_factors', jsonfield.fields.JSONField(default={}, verbose_name='等级经验计算因子')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '艾瑟萌星级',
                'verbose_name_plural': '艾瑟萌星级',
            },
        ),
        migrations.CreateModel(
            name='ExerParamRateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(default=0, verbose_name='最小值')),
                ('max_value', models.IntegerField(default=0, verbose_name='最大值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ExerStar', verbose_name='艾瑟萌星级')),
            ],
            options={
                'verbose_name': '艾瑟萌属性成长率范围',
                'verbose_name_plural': '艾瑟萌属性成长率范围',
            },
        ),
        migrations.CreateModel(
            name='ExerParamBaseRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(default=0, verbose_name='最小值')),
                ('max_value', models.IntegerField(default=0, verbose_name='最大值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ExerStar', verbose_name='艾瑟萌星级')),
            ],
            options={
                'verbose_name': '艾瑟萌基础属性范围',
                'verbose_name_plural': '艾瑟萌基础属性范围',
            },
        ),
        migrations.CreateModel(
            name='ExerGiftStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='星级颜色')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '艾瑟萌天赋星级',
                'verbose_name_plural': '艾瑟萌天赋星级',
            },
        ),
        migrations.CreateModel(
            name='ExerGiftParamRateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(default=0, verbose_name='最小值')),
                ('max_value', models.IntegerField(default=0, verbose_name='最大值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ExerGiftStar', verbose_name='艾瑟萌星级')),
            ],
            options={
                'verbose_name': '艾瑟萌天赋属性成长加成率范围',
                'verbose_name_plural': '艾瑟萌天赋属性成长加成率范围',
            },
        ),
        migrations.CreateModel(
            name='ExerEquipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '艾瑟萌装备类型',
                'verbose_name_plural': '艾瑟萌装备类型',
            },
        ),
        migrations.AddField(
            model_name='baseparam',
            name='configure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置'),
        ),
    ]
