# Generated by Django 2.2.6 on 2020-01-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0002_auto_20200126_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparam',
            name='default',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='baseparam',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='exerequiptype',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='exergiftstar',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='exerstar',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='main_version',
            field=models.CharField(max_length=16, unique=True, verbose_name='主版本号'),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='sub_version',
            field=models.CharField(max_length=16, unique=True, verbose_name='副版本号'),
        ),
        migrations.AlterField(
            model_name='humanequiptype',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='usableitemtype',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='描述'),
        ),
    ]
