# Generated by Django 2.2.6 on 2020-01-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0003_auto_20200126_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseparam',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='属性颜色'),
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='科目颜色'),
        ),
    ]
