# Generated by Django 2.2.6 on 2020-06-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0003_auto_20200226_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '学习小贴士'), (2, '游戏小贴士'), (0, '其他小贴士')], default=1, verbose_name='小贴士类型')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '游戏小贴士',
                'verbose_name_plural': '游戏小贴士',
            },
        ),
    ]
