# Generated by Django 2.2.6 on 2020-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0004_auto_20200131_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameversion',
            name='main_version',
            field=models.CharField(max_length=16, verbose_name='主版本号'),
        ),
    ]
