# Generated by Django 2.2.6 on 2020-01-21 15:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_module', '0002_auto_20200121_1544'),
        ('item_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知容器'), (1, '人类背包'), (2, '艾瑟萌背包'), (11, '艾瑟萌碎片背包'), (21, '题目糖背包'), (101, '人类装备槽'), (102, '艾瑟萌装备槽'), (111, '艾瑟萌槽'), (121, '艾瑟萌技能槽'), (201, '艾瑟萌天赋池'), (202, '艾瑟萌仓库')], default=0, verbose_name='容器类型')),
            ],
            options={
                'verbose_name': '基本容器',
                'verbose_name_plural': '基本容器',
            },
        ),
        migrations.CreateModel(
            name='BaseContItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知容器物品'), (1, '人类背包物品项'), (2, '艾瑟萌背包物品项'), (3, '人类背包装备项'), (4, '艾瑟萌背包装备项'), (11, '艾瑟萌碎片背包项'), (21, '题目糖背包项'), (101, '人类装备槽项'), (102, '艾瑟萌装备槽项'), (111, '艾瑟萌槽项'), (121, '艾瑟萌技能槽项'), (201, '艾瑟萌天赋池项'), (202, '艾瑟萌仓库项')], default=0, verbose_name='容器类型')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_module.BaseContainer', verbose_name='容器')),
            ],
            options={
                'verbose_name': '基本容器物品',
                'verbose_name_plural': '基本容器物品',
            },
        ),
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知物品'), (1, '人类物品'), (2, '艾瑟萌物品'), (11, '人类装备'), (12, '艾瑟萌装备'), (101, '题目糖'), (201, '艾瑟萌'), (202, '艾瑟萌技能'), (203, '艾瑟萌天赋'), (204, '艾瑟萌碎片')], default=0, verbose_name='物品类型')),
            ],
            options={
                'verbose_name': '基础物品',
                'verbose_name_plural': '基础物品',
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='点券')),
                ('bound_ticket', models.PositiveIntegerField(default=0, verbose_name='金币')),
            ],
            options={
                'verbose_name': '物品价格',
                'verbose_name_plural': '物品价格',
            },
        ),
        migrations.CreateModel(
            name='LimitedItem',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseItem')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='出售价格')),
                ('discardable', models.BooleanField(default=True, verbose_name='可丢弃')),
                ('tradable', models.BooleanField(default=True, verbose_name='能否交易')),
                ('icon', models.ImageField(upload_to=utils.model_utils.ItemIconUpload(), verbose_name='图标')),
                ('buy_price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_module.ItemPrice', verbose_name='购入价格')),
            ],
            options={
                'verbose_name': '有限物品',
                'verbose_name_plural': '有限物品',
            },
            bases=('item_module.baseitem',),
        ),
        migrations.CreateModel(
            name='PackContainer',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContainer')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='容量')),
            ],
            options={
                'verbose_name': '背包类容器',
                'verbose_name_plural': '背包类容器',
            },
            bases=('item_module.basecontainer',),
        ),
        migrations.CreateModel(
            name='PackContItem',
            fields=[
                ('basecontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContItem')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='叠加数量')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_module.BaseItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '背包类容器项',
                'verbose_name_plural': '背包类容器项',
            },
            bases=('item_module.basecontitem',),
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '无特性')], default=0, verbose_name='特性编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='特性参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_module.BaseItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '特性',
                'verbose_name_plural': '特性',
            },
        ),
        migrations.CreateModel(
            name='EquipableItem',
            fields=[
                ('limiteditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.LimitedItem')),
            ],
            options={
                'verbose_name': '可装备物品',
                'verbose_name_plural': '可装备物品',
            },
            bases=('item_module.limiteditem',),
        ),
        migrations.CreateModel(
            name='SlotContItem',
            fields=[
                ('basecontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContItem')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='槽编号')),
                ('equip_item1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_item1', to='item_module.PackContItem', verbose_name='装备项1')),
                ('equip_item2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_item2', to='item_module.PackContItem', verbose_name='装备项2')),
            ],
            options={
                'verbose_name': '槽类容器项',
                'verbose_name_plural': '槽类容器项',
            },
            bases=('item_module.basecontitem',),
        ),
        migrations.CreateModel(
            name='SlotContainer',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContainer')),
                ('equip_container1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_container1', to='item_module.PackContainer', verbose_name='装备容器1')),
                ('equip_container2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equip_container2', to='item_module.PackContainer', verbose_name='装备容器2')),
            ],
            options={
                'verbose_name': '槽类容器',
                'verbose_name_plural': '槽类容器',
            },
            bases=('item_module.basecontainer',),
        ),
        migrations.CreateModel(
            name='UsableItem',
            fields=[
                ('limiteditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.LimitedItem')),
                ('max_count', models.PositiveSmallIntegerField(default=99, verbose_name='叠加数量')),
                ('battle_use', models.BooleanField(default=True, verbose_name='对战道具')),
                ('menu_use', models.BooleanField(default=True, verbose_name='背包道具')),
                ('adventure_use', models.BooleanField(default=True, verbose_name='冒险道具')),
                ('consumable', models.BooleanField(default=False, verbose_name='消耗品')),
                ('freeze', models.PositiveSmallIntegerField(default=0, verbose_name='冻结回合')),
                ('i_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.UsableItemType', verbose_name='物品类型')),
            ],
            options={
                'verbose_name': '可用物品',
                'verbose_name_plural': '可用物品',
            },
            bases=('item_module.limiteditem',),
        ),
        migrations.CreateModel(
            name='ItemEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '无效果')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_module.UsableItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '物品使用效果',
                'verbose_name_plural': '物品使用效果',
            },
        ),
        migrations.CreateModel(
            name='EquipParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_module.EquipableItem', verbose_name='装备')),
            ],
            options={
                'verbose_name': '装备属性值',
                'verbose_name_plural': '装备属性值',
            },
        ),
    ]
