# Generated by Django 2.2.6 on 2020-02-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='点券')),
                ('bound_ticket', models.PositiveIntegerField(default=0, verbose_name='金币')),
            ],
            options={
                'verbose_name': '货币',
                'verbose_name_plural': '货币',
            },
        ),
    ]
