# Generated by Django 2.2.6 on 2020-01-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exermon_module', '0001_initial'),
        ('item_module', '0001_initial'),
        ('game_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerequipslot',
            name='exermon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSlotItem', verbose_name='艾瑟萌'),
        ),
        migrations.CreateModel(
            name='ExerItem',
            fields=[
                ('usableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.UsableItem')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='使用几率')),
            ],
            options={
                'verbose_name': '艾瑟萌物品',
                'verbose_name_plural': '艾瑟萌物品',
            },
            bases=('item_module.usableitem',),
        ),
        migrations.CreateModel(
            name='HumanItem',
            fields=[
                ('usableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.UsableItem')),
            ],
            options={
                'verbose_name': '人类物品',
                'verbose_name_plural': '人类物品',
            },
            bases=('item_module.usableitem',),
        ),
        migrations.AddField(
            model_name='usableitem',
            name='i_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.UsableItemType', verbose_name='物品类型'),
        ),
        migrations.AddField(
            model_name='itemeffect',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_module.UsableItem', verbose_name='物品'),
        ),
        migrations.AddField(
            model_name='humanequipslotitem',
            name='e_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.HumanEquipType', verbose_name='装备槽类型'),
        ),
        migrations.AddField(
            model_name='humanequipslotitem',
            name='pack_equip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item_module.HumanPackEquip', verbose_name='人类背包装备'),
        ),
        migrations.AddField(
            model_name='exerequipslotitem',
            name='e_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ExerEquipType', verbose_name='装备槽类型'),
        ),
        migrations.AddField(
            model_name='exerequipslotitem',
            name='pack_equip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item_module.ExerPackEquip', verbose_name='艾瑟萌背包装备'),
        ),
        migrations.AddField(
            model_name='equipparam',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_module.EquipableItem', verbose_name='装备'),
        ),
        migrations.CreateModel(
            name='ExerEquip',
            fields=[
                ('equipableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.EquipableItem')),
                ('e_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ExerEquipType', verbose_name='装备类型')),
            ],
            options={
                'verbose_name': '艾瑟萌装备',
                'verbose_name_plural': '艾瑟萌装备',
            },
            bases=('item_module.equipableitem',),
        ),
    ]
