# Generated by Django 2.2.6 on 2020-01-26 18:33

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('item_module', '0002_basecontainer_basecontitem_baseitem_equipableitem_equipparam_itemeffect_itemprice_limiteditem_packco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='limiteditem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.ItemIconUpload(), verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='limiteditem',
            name='tradable',
            field=models.BooleanField(default=True, verbose_name='可交易'),
        ),
    ]
