# Generated by Django 2.2.6 on 2020-01-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_module', '0002_auto_20200109_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontitem',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_module.BaseContainer', verbose_name='容器'),
        ),
    ]
