# Generated by Django 2.2.6 on 2020-01-27 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_module', '0003_auto_20200126_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecontitem',
            options={'verbose_name': '基本容器项', 'verbose_name_plural': '基本容器项'},
        ),
        migrations.RemoveField(
            model_name='limiteditem',
            name='buy_price',
        ),
        migrations.AddField(
            model_name='itemprice',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_module.LimitedItem', verbose_name='物品'),
        ),
    ]
