# Generated by Django 2.2.6 on 2019-11-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未设置'), (1, '男'), (2, '女'), (3, '不明')], default=0, verbose_name='性别')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, '未设置'), (1, '初中及以下'), (2, '高一'), (3, '高二'), (4, '高三'), (5, '高三复读'), (6, '大学及以上')], default=0, verbose_name='年级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='刷新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '离线'), (1, '在线'), (2, '封禁'), (3, '冻结'), (-1, '其他')], default=0, verbose_name='账号状态')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '标准用户'), (1, 'QQ用户'), (2, '微信用户'), (-1, '其他')], default=0, verbose_name='账号类型')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标志')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
        ),
        migrations.CreateModel(
            name='PasswordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('password', models.CharField(max_length=64, verbose_name='新密码')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '改密记录',
                'verbose_name_plural': '改密记录',
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='登陆时间')),
                ('logout', models.DateTimeField(null=True, verbose_name='登出时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
            },
        ),
    ]
