# Generated by Django 2.2.6 on 2020-08-22 00:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.cache_utils
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_module', '0002_itemprice'),
        ('game_module', '0002_auto_20200822_0008'),
        ('player_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未设置'), (1, '男'), (2, '女'), (3, '不明')], default=0, verbose_name='性别')),
                ('bust', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('bust'), verbose_name='半身像')),
                ('face', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('face'), verbose_name='头像')),
                ('battle', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('battle'), verbose_name='战斗图')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('icon_index', models.PositiveSmallIntegerField(default=0, verbose_name='图标索引')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='出售价格')),
                ('discardable', models.BooleanField(default=True, verbose_name='可丢弃')),
                ('tradable', models.BooleanField(default=True, verbose_name='可交易')),
                ('senior_flag', models.BooleanField(blank=True, null=True, verbose_name='高级标志')),
                ('max_count', models.PositiveSmallIntegerField(default=99, verbose_name='叠加数量')),
                ('battle_use', models.BooleanField(default=True, verbose_name='对战道具')),
                ('menu_use', models.BooleanField(default=True, verbose_name='背包道具')),
                ('adventure_use', models.BooleanField(default=True, verbose_name='冒险道具')),
                ('target', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '人物'), (2, '艾瑟萌')], default=0, verbose_name='使用目标')),
                ('batch_count', models.PositiveSmallIntegerField(default=0, verbose_name='使用个数')),
                ('consumable', models.BooleanField(default=False, verbose_name='消耗品')),
                ('freeze', models.PositiveSmallIntegerField(default=0, verbose_name='冻结回合')),
                ('i_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameItemType', verbose_name='物品类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ItemStar', verbose_name='星级')),
            ],
            options={
                'verbose_name': '可用物品',
                'verbose_name_plural': '可用物品',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='容量')),
            ],
            options={
                'verbose_name': '背包类容器',
                'verbose_name_plural': '背包类容器',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, '不详'), (1, '初中及以下'), (2, '高一'), (3, '高二'), (4, '高三'), (5, '高三复读'), (6, '大学及以上')], default=0, verbose_name='年级')),
                ('subject_selection', jsonfield.fields.JSONField(default=[], verbose_name='选科')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('birth', models.DateField(blank=True, default=datetime.date(1988, 1, 1), null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=24, null=True, verbose_name='学校')),
                ('city', models.CharField(blank=True, max_length=24, null=True, verbose_name='地区')),
                ('contact', models.CharField(blank=True, max_length=24, null=True, verbose_name='联系方式')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='个人介绍')),
                ('credit', models.PositiveSmallIntegerField(default=100, verbose_name='信誉积分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='刷新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未创建'), (2, '已创建人物'), (3, '已选择艾瑟萌'), (4, '已选择天赋'), (10, '正常'), (20, '封禁'), (30, '冻结'), (0, '其他')], default=1, verbose_name='账号状态')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '标准用户'), (1, 'QQ用户'), (2, '微信用户'), (-1, '其他')], default=10, verbose_name='账号类型')),
                ('online', models.BooleanField(default=False, verbose_name='在线')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.Character', verbose_name='人物')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='PlayerMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='点券')),
                ('bound_ticket', models.PositiveIntegerField(default=0, verbose_name='绑定点券')),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '玩家金钱',
                'verbose_name_plural': '玩家金钱',
            },
        ),
        migrations.CreateModel(
            name='PasswordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('password', models.CharField(max_length=64, verbose_name='新密码')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '改密记录',
                'verbose_name_plural': '改密记录',
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='登陆时间')),
                ('logout', models.DateTimeField(null=True, verbose_name='登出时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
            },
        ),
        migrations.CreateModel(
            name='ItemPackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='叠加数量')),
                ('equiped', models.BooleanField(default=False, verbose_name='是否装备中')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.ItemPack', verbose_name='容器')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.GameItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '背包类容器项',
                'verbose_name_plural': '背包类容器项',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.AddField(
            model_name='itempack',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家'),
        ),
        migrations.CreateModel(
            name='GameItemPrice',
            fields=[
                ('itemprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.ItemPrice')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.GameItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '人类物品价格',
                'verbose_name_plural': '人类物品价格',
            },
            bases=('item_module.itemprice',),
        ),
        migrations.CreateModel(
            name='GameItemEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (10, '回复体力值'), (11, '回复精力值'), (20, '增加能力值'), (21, '临时增加能力值'), (22, '战斗中增加能力值'), (30, '获得物品'), (31, '获得金币'), (32, '获得绑定点券'), (40, '指定艾瑟萌获得经验'), (41, '指定艾瑟萌槽项获得经验'), (42, '玩家获得经验'), (99, '执行程序')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.GameItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '人类物品使用效果',
                'verbose_name_plural': '人类物品使用效果',
            },
        ),
    ]
