# Generated by Django 2.2.6 on 2020-02-24 23:04

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_module', '0002_auto_20200224_2304'),
        ('player_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未设置'), (1, '男'), (2, '女'), (3, '不明')], default=0, verbose_name='性别')),
                ('bust', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('bust'), verbose_name='半身像')),
                ('face', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('face'), verbose_name='头像')),
                ('battle', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('battle'), verbose_name='战斗图')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
            },
        ),
        migrations.CreateModel(
            name='HumanEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='出售价格')),
                ('discardable', models.BooleanField(default=True, verbose_name='可丢弃')),
                ('tradable', models.BooleanField(default=True, verbose_name='可交易')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.ItemIconUpload(), verbose_name='图标')),
                ('e_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.HumanEquipType', verbose_name='装备类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ItemStar', verbose_name='星级')),
            ],
            options={
                'verbose_name': '人类装备',
                'verbose_name_plural': '人类装备',
            },
        ),
        migrations.CreateModel(
            name='HumanEquipSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '人类装备槽',
                'verbose_name_plural': '人类装备槽',
            },
        ),
        migrations.CreateModel(
            name='HumanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='出售价格')),
                ('discardable', models.BooleanField(default=True, verbose_name='可丢弃')),
                ('tradable', models.BooleanField(default=True, verbose_name='可交易')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.model_utils.ItemIconUpload(), verbose_name='图标')),
                ('max_count', models.PositiveSmallIntegerField(default=99, verbose_name='叠加数量')),
                ('battle_use', models.BooleanField(default=True, verbose_name='对战道具')),
                ('menu_use', models.BooleanField(default=True, verbose_name='背包道具')),
                ('adventure_use', models.BooleanField(default=True, verbose_name='冒险道具')),
                ('consumable', models.BooleanField(default=False, verbose_name='消耗品')),
                ('freeze', models.PositiveSmallIntegerField(default=0, verbose_name='冻结回合')),
                ('i_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.UsableItemType', verbose_name='物品类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.ItemStar', verbose_name='星级')),
            ],
            options={
                'verbose_name': '人类物品',
                'verbose_name_plural': '人类物品',
            },
        ),
        migrations.CreateModel(
            name='HumanPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='容量')),
            ],
            options={
                'verbose_name': '人类背包',
                'verbose_name_plural': '人类背包',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, '不详'), (1, '初中及以下'), (2, '高一'), (3, '高二'), (4, '高三'), (5, '高三复读'), (6, '大学及以上')], default=0, verbose_name='年级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='刷新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未创建'), (1, '已创建人物'), (2, '已选择艾瑟萌'), (3, '已选择天赋'), (10, '正常'), (20, '封禁'), (30, '冻结'), (-1, '其他')], default=0, verbose_name='账号状态')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '标准用户'), (1, 'QQ用户'), (2, '微信用户'), (-1, '其他')], default=10, verbose_name='账号类型')),
                ('online', models.BooleanField(default=False, verbose_name='在线')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=24, null=True, verbose_name='学校')),
                ('city', models.CharField(blank=True, max_length=24, null=True, verbose_name='地区')),
                ('contact', models.CharField(blank=True, max_length=24, null=True, verbose_name='联系方式')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='个人介绍')),
                ('credit', models.PositiveSmallIntegerField(default=100, verbose_name='信誉积分')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标志')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.Character', verbose_name='人物')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
        ),
        migrations.CreateModel(
            name='PlayerMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='点券')),
                ('bound_ticket', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '玩家金钱',
                'verbose_name_plural': '玩家金钱',
            },
        ),
        migrations.CreateModel(
            name='PasswordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('password', models.CharField(max_length=64, verbose_name='新密码')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '改密记录',
                'verbose_name_plural': '改密记录',
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='登陆时间')),
                ('logout', models.DateTimeField(null=True, verbose_name='登出时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
            },
        ),
        migrations.CreateModel(
            name='HumanPackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='叠加数量')),
                ('equiped', models.BooleanField(default=False, verbose_name='是否装备中')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.containers.ItemPack', verbose_name='容器')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.items.GameItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '人类背包物品',
                'verbose_name_plural': '人类背包物品',
            },
        ),
        migrations.CreateModel(
            name='HumanPackEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='叠加数量')),
                ('equiped', models.BooleanField(default=False, verbose_name='是否装备中')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.containers.ItemPack', verbose_name='容器')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.HumanEquip', verbose_name='物品')),
            ],
            options={
                'verbose_name': '人类背包装备',
                'verbose_name_plural': '人类背包装备',
            },
        ),
        migrations.AddField(
            model_name='humanpack',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家'),
        ),
        migrations.CreateModel(
            name='HumanItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='点券')),
                ('bound_ticket', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.items.GameItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '人类物品价格',
                'verbose_name_plural': '人类物品价格',
            },
        ),
        migrations.CreateModel(
            name='HumanItemEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '空'), (10, '回复体力值'), (11, '回复精力值'), (20, '增加能力值'), (21, '临时增加能力值'), (22, '战斗中增加能力值'), (30, '获得物品'), (31, '获得金币'), (32, '获得绑定点券'), (40, '指定艾瑟萌获得经验'), (41, '指定艾瑟萌槽项获得经验'), (42, '玩家获得经验'), (99, '执行程序')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.items.GameItem', verbose_name='物品')),
            ],
            options={
                'verbose_name': '人类物品使用效果',
                'verbose_name_plural': '人类物品使用效果',
            },
        ),
        migrations.CreateModel(
            name='HumanEquipSlotItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='槽编号')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.HumanEquipSlot', verbose_name='容器')),
                ('e_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.HumanEquipType', verbose_name='装备槽类型')),
                ('pack_equip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player_module.HumanPackEquip', verbose_name='装备')),
            ],
            options={
                'verbose_name': '人类装备槽项',
                'verbose_name_plural': '人类装备槽项',
            },
        ),
        migrations.AddField(
            model_name='humanequipslot',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家'),
        ),
        migrations.CreateModel(
            name='HumanEquipPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='点券')),
                ('bound_ticket', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.HumanEquip', verbose_name='物品')),
            ],
            options={
                'verbose_name': '人类装备价格',
                'verbose_name_plural': '人类装备价格',
            },
        ),
        migrations.CreateModel(
            name='HumanEquipParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.HumanEquip', verbose_name='装备')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
            ],
            options={
                'verbose_name': '人类装备属性值',
                'verbose_name_plural': '人类装备属性值',
            },
        ),
    ]
