# Generated by Django 2.2.6 on 2020-01-21 15:44

from django.db import migrations, models
import django.db.models.deletion
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_module', '0002_auto_20200121_1544'),
        ('item_module', '0002_basecontainer_basecontitem_baseitem_equipableitem_equipparam_itemeffect_itemprice_limiteditem_packco'),
        ('player_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未设置'), (1, '男'), (2, '女'), (3, '不明')], default=0, verbose_name='性别')),
                ('bust', models.ImageField(upload_to=utils.model_utils.CharacterImageUpload('bust'), verbose_name='半身像')),
                ('face', models.ImageField(upload_to=utils.model_utils.CharacterImageUpload('face'), verbose_name='头像')),
                ('battle', models.ImageField(upload_to=utils.model_utils.CharacterImageUpload('battle'), verbose_name='战斗图')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
            },
        ),
        migrations.CreateModel(
            name='HumanItem',
            fields=[
                ('usableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.UsableItem')),
            ],
            options={
                'verbose_name': '人类物品',
                'verbose_name_plural': '人类物品',
            },
            bases=('item_module.usableitem',),
        ),
        migrations.CreateModel(
            name='HumanPackItem',
            fields=[
                ('packcontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.PackContItem')),
            ],
            options={
                'verbose_name': '人类背包物品',
                'verbose_name_plural': '人类背包物品',
            },
            bases=('item_module.packcontitem',),
        ),
        migrations.CreateModel(
            name='HumanPackEquip',
            fields=[
                ('humanpackitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player_module.HumanPackItem')),
            ],
            options={
                'verbose_name': '人类背包装备',
                'verbose_name_plural': '人类背包装备',
            },
            bases=('player_module.humanpackitem',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, '未设置'), (1, '初中及以下'), (2, '高一'), (3, '高二'), (4, '高三'), (5, '高三复读'), (6, '大学及以上')], default=0, verbose_name='年级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='刷新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '离线'), (1, '在线'), (2, '封禁'), (3, '冻结'), (-1, '其他')], default=0, verbose_name='账号状态')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '标准用户'), (1, 'QQ用户'), (2, '微信用户'), (-1, '其他')], default=0, verbose_name='账号类型')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=12, null=True, verbose_name='学校')),
                ('city', models.CharField(blank=True, max_length=12, null=True, verbose_name='地区')),
                ('contact', models.CharField(blank=True, max_length=24, null=True, verbose_name='联系方式')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='个人介绍')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标志')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.Character', verbose_name='人物')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
            },
        ),
        migrations.CreateModel(
            name='PasswordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('password', models.CharField(max_length=64, verbose_name='新密码')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '改密记录',
                'verbose_name_plural': '改密记录',
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='登陆时间')),
                ('logout', models.DateTimeField(null=True, verbose_name='登出时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '登录记录',
                'verbose_name_plural': '登录记录',
            },
        ),
        migrations.CreateModel(
            name='HumanPack',
            fields=[
                ('packcontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.PackContainer')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '人类背包',
                'verbose_name_plural': '人类背包',
            },
            bases=('item_module.packcontainer',),
        ),
        migrations.CreateModel(
            name='HumanEquipSlotItem',
            fields=[
                ('slotcontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.SlotContItem')),
                ('e_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.HumanEquipType', verbose_name='装备槽类型')),
            ],
            options={
                'verbose_name': '人类装备槽项',
                'verbose_name_plural': '人类装备槽项',
            },
            bases=('item_module.slotcontitem',),
        ),
        migrations.CreateModel(
            name='HumanEquipSlot',
            fields=[
                ('slotcontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.SlotContainer')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '人类装备槽',
                'verbose_name_plural': '人类装备槽',
            },
            bases=('item_module.slotcontainer',),
        ),
        migrations.CreateModel(
            name='HumanEquip',
            fields=[
                ('equipableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.EquipableItem')),
                ('e_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.HumanEquipType', verbose_name='装备类型')),
            ],
            options={
                'verbose_name': '人类装备',
                'verbose_name_plural': '人类装备',
            },
            bases=('item_module.equipableitem',),
        ),
    ]
