# Generated by Django 2.2.6 on 2020-02-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0002_auto_20200218_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanequipslotitem',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.HumanEquipSlot', verbose_name='容器'),
        ),
    ]
