# Generated by Django 2.2.6 on 2020-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0002_auto_20200224_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未创建'), (2, '已创建人物'), (3, '已选择艾瑟萌'), (4, '已选择天赋'), (10, '正常'), (20, '封禁'), (30, '冻结'), (0, '其他')], default=1, verbose_name='账号状态'),
        ),
    ]
