# Generated by Django 2.2.6 on 2020-01-26 18:33

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0002_character_humanequip_humanequipslot_humanequipslotitem_humanitem_humanpack_humanpackequip_humanpacki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='battle',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('battle'), verbose_name='战斗图'),
        ),
        migrations.AlterField(
            model_name='character',
            name='bust',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('bust'), verbose_name='半身像'),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='character',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.CharacterImageUpload('face'), verbose_name='头像'),
        ),
    ]
