# Generated by Django 2.2.6 on 2020-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0003_humanequipslotitem_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanpackequip',
            name='equiped',
            field=models.BooleanField(default=False, verbose_name='是否装备中'),
        ),
        migrations.AddField(
            model_name='humanpackitem',
            name='equiped',
            field=models.BooleanField(default=False, verbose_name='是否装备中'),
        ),
    ]
