# Generated by Django 2.2.6 on 2020-01-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0003_auto_20200126_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='online',
            field=models.BooleanField(default=False, verbose_name='在线'),
        ),
        migrations.AlterField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(0, '不详'), (1, '初中及以下'), (2, '高一'), (3, '高二'), (4, '高三'), (5, '高三复读'), (6, '大学及以上')], default=0, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='player',
            name='school',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未创建'), (1, '已创建人物'), (2, '已选择艾瑟萌'), (3, '已选择天赋'), (10, '正常'), (20, '封禁'), (30, '冻结'), (-1, '其他')], default=0, verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='player',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, '标准用户'), (1, 'QQ用户'), (2, '微信用户'), (-1, '其他')], default=10, verbose_name='账号类型'),
        ),
    ]
