# Generated by Django 2.2.6 on 2020-03-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0003_auto_20200226_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanequip',
            name='min_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='最低等级'),
        ),
        migrations.AddField(
            model_name='humanequip',
            name='param_rate',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='属性比率'),
        ),
        migrations.AddField(
            model_name='humanequip',
            name='param_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '无类型'), (1, '攻击型'), (2, '防御型')], default=0, verbose_name='属性类型'),
        ),
    ]
