# Generated by Django 2.2.6 on 2020-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0004_auto_20200130_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='经验值'),
        ),
    ]
