# Generated by Django 2.2.6 on 2020-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0004_auto_20200218_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='credit',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='信誉积分'),
        ),
    ]
