# Generated by Django 2.2.6 on 2020-05-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0003_auto_20200226_1009'),
        ('player_module', '0007_auto_20200430_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanequip',
            name='param_rate',
        ),
        migrations.RemoveField(
            model_name='humanequip',
            name='param_type',
        ),
        migrations.CreateModel(
            name='HumanEquipLevelParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.HumanEquip', verbose_name='装备')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
            ],
            options={
                'verbose_name': '人类装备等级属性值',
                'verbose_name_plural': '人类装备等级属性值',
            },
        ),
    ]
