# Generated by Django 2.2.6 on 2020-05-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0009_auto_20200505_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanitem',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '人物'), (2, '艾瑟萌')], default=0, verbose_name='使用目标'),
        ),
    ]
