# Generated by Django 2.2.6 on 2020-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0010_humanitem_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanitem',
            name='batch_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='使用个数'),
        ),
    ]
