# Generated by Django 2.2.6 on 2020-05-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0011_humanitem_batch_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanequipprice',
            name='bound_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='绑定点券'),
        ),
        migrations.AlterField(
            model_name='humanitemprice',
            name='bound_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='绑定点券'),
        ),
        migrations.AlterField(
            model_name='playermoney',
            name='bound_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='绑定点券'),
        ),
    ]
