# Generated by Django 2.2.6 on 2020-04-30 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0012_auto_20200509_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.DateField(default=datetime.date(1988, 1, 1), verbose_name='生日'),
        ),
    ]
