# Generated by Django 2.2.6 on 2020-05-10 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0013_auto_20200510_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.DateField(blank=True, default=datetime.date(1988, 1, 1), null=True, verbose_name='生日'),
        ),
    ]
