# Generated by Django 2.2.6 on 2020-07-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_module', '0014_auto_20200510_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanequip',
            options={'verbose_name': '可装备物品', 'verbose_name_plural': '可装备物品'},
        ),
        migrations.AlterModelOptions(
            name='humanequipslot',
            options={'verbose_name': '槽类容器', 'verbose_name_plural': '槽类容器'},
        ),
        migrations.AlterModelOptions(
            name='humanequipslotitem',
            options={'verbose_name': '槽类容器项', 'verbose_name_plural': '槽类容器项'},
        ),
        migrations.AlterModelOptions(
            name='humanitem',
            options={'verbose_name': '可用物品', 'verbose_name_plural': '可用物品'},
        ),
        migrations.AlterModelOptions(
            name='humanpack',
            options={'verbose_name': '背包类容器', 'verbose_name_plural': '背包类容器'},
        ),
        migrations.AlterModelOptions(
            name='humanpackequip',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.AlterModelOptions(
            name='humanpackitem',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.AlterField(
            model_name='humanequipslotitem',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.HumanEquipSlot', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='humanequipslotitem',
            name='pack_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player_module.HumanPackEquip', verbose_name='人类背包装备'),
        ),
        migrations.AlterField(
            model_name='humanpackequip',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.containers.ItemPack', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='humanpackequip',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.items.GameItem', verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='humanpackitem',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.containers.ItemPack', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='humanpackitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.item_system.items.GameItem', verbose_name='物品'),
        ),
    ]
