# Generated by Django 2.2.6 on 2020-03-22 18:16

import battle_module.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
