# Generated by Django 2.2.6 on 2020-03-22 18:16

import battle_module.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exermon_module', '0004_auto_20200322_1816'),
        ('question_module', '0003_auto_20200226_1009'),
        ('game_module', '0003_auto_20200226_1009'),
        ('season_module', '0002_comprank_compseason_seasonrecord_suspensionrecord'),
        ('player_module', '0004_auto_20200322_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleItemSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '对战物资槽',
                'verbose_name_plural': '对战物资槽',
            },
        ),
        migrations.CreateModel(
            name='BattlePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('exp_incr', models.SmallIntegerField(null=True, verbose_name='经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('slot_exp_incr', models.SmallIntegerField(null=True, verbose_name='槽经验增加')),
                ('finished', models.BooleanField(default=False, verbose_name='完成标志')),
                ('score_incr', models.SmallIntegerField(null=True, verbose_name='积分变更')),
                ('time_score', models.PositiveSmallIntegerField(null=True, verbose_name='用时评分')),
                ('hurt_score', models.PositiveSmallIntegerField(null=True, verbose_name='伤害评分')),
                ('damage_score', models.PositiveSmallIntegerField(null=True, verbose_name='承伤评分')),
                ('recover_score', models.PositiveSmallIntegerField(null=True, verbose_name='恢复评分')),
                ('correct_score', models.PositiveSmallIntegerField(null=True, verbose_name='行动评分')),
                ('plus_score', models.PositiveSmallIntegerField(null=True, verbose_name='奖励分数')),
                ('result', models.PositiveSmallIntegerField(choices=[(1, '胜利'), (2, '失败'), (3, '平局')], null=True, verbose_name='战斗结果')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '正常'), (1, '掉线'), (2, '退出')], null=True, verbose_name='战斗状态标志')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '对战玩家',
                'verbose_name_plural': '对战玩家',
            },
        ),
        migrations.CreateModel(
            name='BattleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, '经典模式')], default=0, verbose_name='对战模式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='对战时间')),
                ('result_time', models.DateTimeField(null=True, verbose_name='结算时间')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season_module.CompSeason', verbose_name='赛季')),
            ],
            options={
                'verbose_name': '对战记录',
                'verbose_name_plural': '对战记录',
            },
        ),
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='回合号')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question_module.models.GeneralQuestion', verbose_name='题目')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_module.BattleRecord', verbose_name='对战记录')),
            ],
            options={
                'verbose_name': '对战回合',
                'verbose_name_plural': '对战回合',
            },
        ),
        migrations.CreateModel(
            name='BattleRoundResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', jsonfield.fields.JSONField(default=[], verbose_name='选择情况')),
                ('answered', models.BooleanField(default=False, verbose_name='作答标志')),
                ('timespan', models.PositiveIntegerField(default=0, verbose_name='用时')),
                ('exp_incr', models.SmallIntegerField(null=True, verbose_name='经验增加')),
                ('slot_exp_incr', models.SmallIntegerField(null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('is_new', models.BooleanField(default=False, verbose_name='新题标志')),
                ('attack', models.BooleanField(null=True, verbose_name='是否进攻')),
                ('target_type', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '己方'), (2, '敌方'), (3, '双方随机'), (4, '双方全部')], default=2, verbose_name='目标')),
                ('result_type', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '命中'), (2, '暴击'), (3, '回避')], default=0, verbose_name='回合结果')),
                ('hurt', models.SmallIntegerField(default=0, verbose_name='伤害点数')),
                ('damage', models.SmallIntegerField(default=0, verbose_name='承伤点数')),
                ('recover', models.PositiveSmallIntegerField(default=0, verbose_name='回复点数')),
                ('battle_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_module.BattlePlayer', verbose_name='对战玩家')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.models.GeneralQuestion', verbose_name='题目')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_module.BattleRound', verbose_name='回合')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exermon_module.ExerSkill', verbose_name='使用技能')),
            ],
            options={
                'verbose_name': '对战回合结果',
                'verbose_name_plural': '对战回合结果',
            },
        ),
        migrations.CreateModel(
            name='BattleResultJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='描述')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='评价分数')),
                ('win', models.SmallIntegerField(default=0, verbose_name='胜利增星数')),
                ('lose', models.SmallIntegerField(default=0, verbose_name='失败增星数')),
                ('configure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.GameConfigure', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '对战评价表',
                'verbose_name_plural': '对战评价表',
            },
        ),
        migrations.AddField(
            model_name='battleplayer',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_module.BattleRecord', verbose_name='对战记录'),
        ),
        migrations.CreateModel(
            name='BattleItemSlotItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='槽编号')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_module.BattleItemSlot', verbose_name='容器')),
                ('pack_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player_module.item_system.cont_items.ItemPackItem', verbose_name='装备')),
            ],
            options={
                'verbose_name': '人类装备槽项',
                'verbose_name_plural': '人类装备槽项',
            },
        ),
    ]
