# Generated by Django 2.2.6 on 2020-07-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_module', '0002_auto_20200421_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battleitemslot',
            options={'verbose_name': '槽类容器', 'verbose_name_plural': '槽类容器'},
        ),
        migrations.AlterModelOptions(
            name='battleitemslotitem',
            options={'verbose_name': '槽类容器项', 'verbose_name_plural': '槽类容器项'},
        ),
        migrations.AlterField(
            model_name='battleitemslotitem',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_module.BattleItemSlot', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='battleitemslotitem',
            name='pack_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player_module.ItemPackItem', verbose_name='人类背包物品'),
        ),
    ]
