# Generated by Django 2.2.6 on 2020-01-09 22:49

from django.db import migrations, models
import django.db.models.deletion
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_module', '0001_initial'),
        ('game_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='题干')),
                ('description', models.TextField(default='无', verbose_name='题解')),
                ('score', models.PositiveSmallIntegerField(default=6, verbose_name='分值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '判断题'), (-1, '其他题')], default=1, verbose_name='类型')),
                ('for_test', models.BooleanField(default=False, verbose_name='测试')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '正常'), (1, '异常'), (-1, '其他')], default=0, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标志')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='QuestionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4, verbose_name='名称')),
                ('pressure', models.PositiveSmallIntegerField(default=0, verbose_name='压力增加')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='等级权重')),
                ('incre', models.PositiveSmallIntegerField(default=0, verbose_name='增益基数')),
                ('entry', models.PositiveSmallIntegerField(default=0, verbose_name='点数限制')),
                ('std_time', models.PositiveSmallIntegerField(default=0, verbose_name='标准时间（分）')),
                ('min_time', models.PositiveSmallIntegerField(default=0, verbose_name='最短时间（秒）')),
                ('power', models.PositiveSmallIntegerField(default=0, verbose_name='对战威力')),
            ],
            options={
                'verbose_name': '题目等级',
                'verbose_name_plural': '题目等级',
            },
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '题目错误'), (1, '图片错误'), (2, '答案错误'), (3, '科目错误'), (4, '难度分配错误'), (-1, '其他')], verbose_name='类型')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目反馈',
                'verbose_name_plural': '题目反馈',
            },
        ),
        migrations.CreateModel(
            name='QuestionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=utils.model_utils.SystemImageUpload('pictures'), verbose_name='图片文件')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目图片',
                'verbose_name_plural': '题目图片',
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='文本')),
                ('answer', models.BooleanField(default=False, verbose_name='正误')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_module.QuestionLevel', verbose_name='星级'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_module.Subject', verbose_name='科目'),
        ),
    ]
