# Generated by Django 2.2.7 on 2020-06-25 12:48

from django.db import migrations, models
import django.db.models.deletion
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_module', '0001_initial'),
        ('game_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesSugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='出售价格')),
                ('get_rate', models.PositiveSmallIntegerField(default=50, verbose_name='获得概率')),
                ('get_count', models.PositiveSmallIntegerField(default=1, verbose_name='获得个数')),
            ],
            options={
                'verbose_name': '题目糖',
                'verbose_name_plural': '题目糖',
            },
        ),
        migrations.CreateModel(
            name='QuesSugarPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='容量')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '题目糖背包',
                'verbose_name_plural': '题目糖背包',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='题干')),
                ('description', models.TextField(blank=True, null=True, verbose_name='题解')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '判断题'), (-1, '其他题')], default=0, verbose_name='类型')),
                ('for_test', models.BooleanField(default=False, verbose_name='测试')),
                ('source', models.TextField(blank=True, null=True, verbose_name='来源')),
                ('level', models.SmallIntegerField(default=0, verbose_name='附加等级')),
                ('score', models.PositiveSmallIntegerField(default=6, verbose_name='分值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '正常'), (1, '异常'), (-1, '其他')], default=0, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='删除标志')),
                ('star', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_module.QuestionStar', verbose_name='星级')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_module.Subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='QuesSugarPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.PositiveIntegerField(default=0, verbose_name='金币')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='点券')),
                ('bound_ticket', models.PositiveIntegerField(default=0, verbose_name='绑定点券')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question_module.QuesSugar', verbose_name='物品')),
            ],
            options={
                'verbose_name': '题目糖价格',
                'verbose_name_plural': '题目糖价格',
            },
        ),
        migrations.CreateModel(
            name='QuesSugarParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('sugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.QuesSugar', verbose_name='题目糖')),
            ],
            options={
                'verbose_name': '题目糖属性值',
                'verbose_name_plural': '题目糖属性值',
            },
        ),
        migrations.CreateModel(
            name='QuesSugarPackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='叠加数量')),
                ('equiped', models.BooleanField(default=False, verbose_name='是否装备中')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question_module.QuesSugarPack', verbose_name='容器')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question_module.QuesSugar', verbose_name='物品')),
            ],
            options={
                'verbose_name': '题目糖背包物品',
                'verbose_name_plural': '题目糖背包物品',
            },
        ),
        migrations.AddField(
            model_name='quessugar',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question', verbose_name='对应题目'),
        ),
        migrations.CreateModel(
            name='QuesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '题目错误'), (2, '图片错误'), (3, '答案错误'), (4, '解析错误'), (5, '科目错误'), (6, '难度分配错误'), (7, '多个错误'), (0, '其他错误')], verbose_name='类型')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('result', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('result_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目反馈',
                'verbose_name_plural': '题目反馈',
            },
        ),
        migrations.CreateModel(
            name='QuesPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('desc_pic', models.BooleanField(default=False, verbose_name='解析图片')),
                ('file', models.ImageField(upload_to=utils.model_utils.QuestionImageUpload(), verbose_name='图片文件')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目图片',
                'verbose_name_plural': '题目图片',
            },
        ),
        migrations.CreateModel(
            name='QuesChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='编号')),
                ('text', models.TextField(verbose_name='文本')),
                ('answer', models.BooleanField(default=False, verbose_name='正误')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Question', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项',
            },
        ),
    ]
