# Generated by Django 2.2.6 on 2020-01-09 22:49

from django.db import migrations, models
import django.db.models.deletion
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
