# Generated by Django 2.2.6 on 2020-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0002_auto_20200218_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='quessugarpackitem',
            name='equiped',
            field=models.BooleanField(default=False, verbose_name='是否装备中'),
        ),
    ]
