# Generated by Django 2.2.6 on 2020-02-26 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0002_auto_20200224_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesSugarPriceInline',
        ),
        migrations.AddField(
            model_name='quesreport',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='反馈时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quesreport',
            name='result',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='quesreport',
            name='result_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
    ]
