# Generated by Django 2.2.6 on 2020-05-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0006_auto_20200509_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='quespicture',
            name='desc_pic',
            field=models.BooleanField(default=False, verbose_name='解析图片'),
        ),
    ]
