# Generated by Django 2.2.6 on 2020-07-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0007_quespicture_desc_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quessugar',
            options={'verbose_name': '基础物品', 'verbose_name_plural': '基础物品'},
        ),
        migrations.AlterModelOptions(
            name='quessugarpack',
            options={'verbose_name': '背包类容器', 'verbose_name_plural': '背包类容器'},
        ),
        migrations.AlterModelOptions(
            name='quessugarpackitem',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.AlterField(
            model_name='quessugarpackitem',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_module.QuesSugarPack', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='quessugarpackitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_module.QuesSugar', verbose_name='物品'),
        ),
    ]
