# Generated by Django 2.2.6 on 2020-01-09 22:49

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_module', '0001_initial'),
        ('item_module', '0001_initial'),
        ('game_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerFragPackItem',
            fields=[
                ('packcontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.PackContItem')),
            ],
            options={
                'verbose_name': '艾瑟萌碎片背包物品',
                'verbose_name_plural': '艾瑟萌碎片背包物品',
            },
            bases=('item_module.packcontitem',),
        ),
        migrations.CreateModel(
            name='ExerGift',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseItem')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='标志颜色')),
            ],
            options={
                'verbose_name': '艾瑟萌天赋',
                'verbose_name_plural': '艾瑟萌天赋',
            },
            bases=('item_module.baseitem',),
        ),
        migrations.CreateModel(
            name='ExerGiftPool',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContainer')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='容量')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '艾瑟萌天赋池',
                'verbose_name_plural': '艾瑟萌天赋池',
            },
            bases=('item_module.basecontainer',),
        ),
        migrations.CreateModel(
            name='ExerHub',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContainer')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='容量')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '艾瑟萌仓库',
                'verbose_name_plural': '艾瑟萌仓库',
            },
            bases=('item_module.basecontainer',),
        ),
        migrations.CreateModel(
            name='Exermon',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseItem')),
                ('full', models.ImageField(upload_to=utils.model_utils.ExermonImageUpload('full'), verbose_name='全身像')),
                ('icon', models.ImageField(upload_to=utils.model_utils.ExermonImageUpload('icon'), verbose_name='缩略图')),
                ('battle', models.ImageField(upload_to=utils.model_utils.ExermonImageUpload('battle'), verbose_name='战斗图')),
            ],
            options={
                'verbose_name': '艾瑟萌',
                'verbose_name_plural': '艾瑟萌',
            },
            bases=('item_module.baseitem',),
        ),
        migrations.CreateModel(
            name='ExerSkill',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseItem')),
                ('passive', models.BooleanField(default=False, verbose_name='被动技能')),
                ('need_count', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='次数需求')),
                ('mp_cost', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='MP消耗')),
                ('rate', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='使用几率')),
                ('freeze', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='冻结时间')),
                ('max_use_count', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='最大使用次数')),
                ('target', models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '己方'), (2, '敌方'), (3, '双方随机'), (4, '双方全部')], default=2, null=True, verbose_name='目标')),
                ('hit_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, '无'), (1, '体力值伤害'), (2, '体力值回复'), (3, '体力值吸收'), (4, '精力值伤害'), (5, '精力值回复'), (6, '精力值吸收')], default=1, null=True, verbose_name='命中类型')),
                ('atk_rate', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='攻击比率')),
                ('def_rate', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='防御比率')),
                ('plus_formula', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='附加公式')),
                ('icon', models.ImageField(upload_to=utils.model_utils.SkillImageUpload('icon'), verbose_name='图标')),
                ('ani', models.ImageField(upload_to=utils.model_utils.SkillImageUpload('ani'), verbose_name='技能动画')),
                ('effect', models.ImageField(upload_to=utils.model_utils.SkillImageUpload('effect'), verbose_name='击中动画')),
                ('next_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSkill', verbose_name='下级技能')),
                ('o_exermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.Exermon', verbose_name='艾瑟萌')),
            ],
            options={
                'verbose_name': '有限物品',
                'verbose_name_plural': '有限物品',
            },
            bases=('item_module.baseitem',),
        ),
        migrations.CreateModel(
            name='ExerStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='星级名称')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='星级颜色')),
                ('max_level', models.PositiveSmallIntegerField(default=0, verbose_name='最大等级')),
                ('level_exp_factors', jsonfield.fields.JSONField(default={}, verbose_name='等级经验计算因子')),
            ],
            options={
                'verbose_name': '艾瑟萌星级',
                'verbose_name_plural': '艾瑟萌星级',
            },
        ),
        migrations.CreateModel(
            name='PlayerExerGift',
            fields=[
                ('packcontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.PackContItem')),
            ],
            options={
                'verbose_name': '玩家艾瑟萌天赋',
                'verbose_name_plural': '玩家艾瑟萌天赋',
            },
            bases=('item_module.packcontitem',),
        ),
        migrations.CreateModel(
            name='SkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(choices=[(0, '无效果')], default=0, verbose_name='效果编号')),
                ('params', jsonfield.fields.JSONField(default=[], verbose_name='效果参数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSkill', verbose_name='物品')),
            ],
            options={
                'verbose_name': '技能使用效果',
                'verbose_name_plural': '技能使用效果',
            },
        ),
        migrations.CreateModel(
            name='PlayerExermon',
            fields=[
                ('packcontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.PackContItem')),
                ('nickname', models.CharField(max_length=8, verbose_name='艾瑟萌昵称')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='等级')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '玩家艾瑟萌',
                'verbose_name_plural': '玩家艾瑟萌',
            },
            bases=('item_module.packcontitem',),
        ),
        migrations.CreateModel(
            name='GiftParamRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerGift', verbose_name='艾瑟萌天赋')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
            ],
            options={
                'verbose_name': '艾瑟萌天赋成长加成率',
                'verbose_name_plural': '艾瑟萌天赋成长加成率',
            },
        ),
        migrations.CreateModel(
            name='ExerSlotItem',
            fields=[
                ('slotcontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.SlotContItem')),
                ('nickname', models.CharField(max_length=8, verbose_name='艾瑟萌昵称')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('exermon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExermon', verbose_name='玩家艾瑟萌')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExerGift', verbose_name='天赋')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.Subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '艾瑟萌槽项',
                'verbose_name_plural': '艾瑟萌槽项',
            },
            bases=('item_module.slotcontitem',),
        ),
        migrations.CreateModel(
            name='ExerSlot',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContainer')),
                ('exer_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerHub', verbose_name='艾瑟萌仓库')),
                ('gift_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerGiftPool', verbose_name='天赋池')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '艾瑟萌槽',
                'verbose_name_plural': '艾瑟萌槽',
            },
            bases=('item_module.basecontainer',),
        ),
        migrations.CreateModel(
            name='ExerSkillSlotItem',
            fields=[
                ('slotcontitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.SlotContItem')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('exermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExermon', verbose_name='艾瑟萌')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSkill', verbose_name='技能')),
            ],
            options={
                'verbose_name': '艾瑟萌技能槽项',
                'verbose_name_plural': '艾瑟萌技能槽项',
            },
            bases=('item_module.slotcontitem',),
        ),
        migrations.CreateModel(
            name='ExerSkillSlot',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContainer')),
                ('exermon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExermon', verbose_name='艾瑟萌')),
            ],
            options={
                'verbose_name': '艾瑟萌技能槽',
                'verbose_name_plural': '艾瑟萌技能槽',
            },
            bases=('item_module.basecontainer',),
        ),
        migrations.CreateModel(
            name='ExerParamRateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(default=0, verbose_name='最小值')),
                ('max_value', models.IntegerField(default=0, verbose_name='最大值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerStar', verbose_name='艾瑟萌星级')),
            ],
            options={
                'verbose_name': '艾瑟萌属性成长率范围',
                'verbose_name_plural': '艾瑟萌属性成长率范围',
            },
        ),
        migrations.CreateModel(
            name='ExerParamRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('exermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.Exermon', verbose_name='艾瑟萌')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
            ],
            options={
                'verbose_name': '艾瑟萌属性成长率',
                'verbose_name_plural': '艾瑟萌属性成长率',
            },
        ),
        migrations.CreateModel(
            name='ExerParamBaseRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(default=0, verbose_name='最小值')),
                ('max_value', models.IntegerField(default=0, verbose_name='最大值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerStar', verbose_name='艾瑟萌星级')),
            ],
            options={
                'verbose_name': '艾瑟萌基础属性范围',
                'verbose_name_plural': '艾瑟萌基础属性范围',
            },
        ),
        migrations.CreateModel(
            name='ExerParamBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('exermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.Exermon', verbose_name='艾瑟萌')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
            ],
            options={
                'verbose_name': '艾瑟萌基础属性值',
                'verbose_name_plural': '艾瑟萌基础属性值',
            },
        ),
        migrations.AddField(
            model_name='exermon',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerStar', verbose_name='艾瑟萌星级'),
        ),
        migrations.AddField(
            model_name='exermon',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.Subject', verbose_name='科目'),
        ),
        migrations.CreateModel(
            name='ExerFragPack',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseContainer')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name='容量')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '艾瑟萌碎片背包',
                'verbose_name_plural': '艾瑟萌碎片背包',
            },
            bases=('item_module.basecontainer',),
        ),
        migrations.CreateModel(
            name='ExerFrag',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_module.BaseItem')),
                ('count', models.PositiveSmallIntegerField(default=16, verbose_name='所需碎片数')),
                ('sell_price', models.PositiveIntegerField(default=0, verbose_name='出售价格')),
                ('o_exermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.Exermon', verbose_name='所属艾瑟萌')),
            ],
            options={
                'verbose_name': '艾瑟萌碎片',
                'verbose_name_plural': '艾瑟萌碎片',
            },
            bases=('item_module.baseitem',),
        ),
    ]
