# Generated by Django 2.2.6 on 2020-01-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerslot',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家'),
        ),
    ]
