# Generated by Django 2.2.6 on 2020-01-27 14:16

from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0002_exerequip_exerequipslot_exerequipslotitem_exerfrag_exerfragpack_exerfragpackitem_exergift_exergiftpo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerskill',
            options={'verbose_name': '艾瑟萌技能', 'verbose_name_plural': '艾瑟萌技能'},
        ),
        migrations.RemoveField(
            model_name='exergift',
            name='color',
        ),
        migrations.AlterField(
            model_name='exermon',
            name='battle',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.ExermonImageUpload('battle'), verbose_name='战斗图'),
        ),
        migrations.AlterField(
            model_name='exermon',
            name='full',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.ExermonImageUpload('full'), verbose_name='全身像'),
        ),
        migrations.AlterField(
            model_name='exermon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.ExermonImageUpload('icon'), verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='exerskill',
            name='ani',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.SkillImageUpload('ani'), verbose_name='技能动画'),
        ),
        migrations.AlterField(
            model_name='exerskill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.SkillImageUpload('icon'), verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='exerskill',
            name='target_ani',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.SkillImageUpload('effect'), verbose_name='击中动画'),
        ),
    ]
