# Generated by Django 2.2.6 on 2020-01-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0002_auto_20200110_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerslotitem',
            name='exermon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExermon', verbose_name='玩家艾瑟萌'),
        ),
        migrations.AlterField(
            model_name='exerslotitem',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExerGift', verbose_name='天赋'),
        ),
    ]
