# Generated by Django 2.2.6 on 2020-01-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0002_exerequip_exerequipslot_exerequipslotitem_exerfrag_exerfragpack_exerfragpackitem_exergift_exergiftpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerexermon',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家'),
        ),
    ]
