# Generated by Django 2.2.6 on 2020-02-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0002_auto_20200224_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerEquipPriceInline',
        ),
        migrations.DeleteModel(
            name='ExerItemPriceInline',
        ),
    ]
