# Generated by Django 2.2.6 on 2020-02-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0002_auto_20200218_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerequipslotitem',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerEquipSlot', verbose_name='容器'),
        ),
        migrations.AddField(
            model_name='exerskillslotitem',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSkillSlot', verbose_name='容器'),
        ),
        migrations.AddField(
            model_name='exerslotitem',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSlot', verbose_name='容器'),
        ),
    ]
