# Generated by Django 2.2.6 on 2020-03-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0003_auto_20200226_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerequip',
            name='min_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='最低等级'),
        ),
        migrations.AddField(
            model_name='exerequip',
            name='param_rate',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='属性比率'),
        ),
        migrations.AddField(
            model_name='exerequip',
            name='param_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '无类型'), (1, '攻击型'), (2, '防御型')], default=0, verbose_name='属性类型'),
        ),
        migrations.AddField(
            model_name='exerskill',
            name='cri_rate',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='暴击率加成'),
        ),
        migrations.AddField(
            model_name='exerskill',
            name='drain_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='吸收率'),
        ),
        migrations.AddField(
            model_name='exerskill',
            name='hit_rate',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='命中率加成'),
        ),
        migrations.AlterField(
            model_name='exerskill',
            name='plus_formula',
            field=models.CharField(blank=True, default='0', max_length=256, null=True, verbose_name='附加公式'),
        ),
    ]
