# Generated by Django 2.2.6 on 2020-01-22 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0003_auto_20200121_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerequipslot',
            old_name='exermon',
            new_name='exer_slot',
        ),
    ]
