# Generated by Django 2.2.6 on 2020-01-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0004_auto_20200130_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerskill',
            old_name='target',
            new_name='target_type',
        ),
    ]
