# Generated by Django 2.2.6 on 2020-02-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0004_auto_20200218_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='exergift',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='标志颜色'),
        ),
    ]
