# Generated by Django 2.2.6 on 2020-01-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0005_auto_20200122_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerskill',
            name='o_exermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exerskills', to='exermon_module.Exermon', verbose_name='艾瑟萌'),
        ),
    ]
