# Generated by Django 2.2.6 on 2020-04-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0005_auto_20200327_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerequip',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='exeritem',
            name='icon',
        ),
    ]
