# Generated by Django 2.2.6 on 2020-01-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0006_auto_20200122_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerskill',
            name='o_exermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.Exermon', verbose_name='艾瑟萌'),
        ),
        migrations.AlterField(
            model_name='exerskillslotitem',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSkill', verbose_name='技能'),
        ),
    ]
