# Generated by Django 2.2.6 on 2020-05-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0003_auto_20200226_1009'),
        ('exermon_module', '0008_auto_20200505_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeritem',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '人物'), (2, '艾瑟萌')], default=0, verbose_name='使用目标'),
        ),
        migrations.CreateModel(
            name='PlayerExerParamRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('expires_time', models.DateTimeField(null=True, verbose_name='过期时间')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('player_exer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExermon', verbose_name='玩家艾瑟萌')),
            ],
            options={
                'verbose_name': '玩家艾瑟萌属性加成',
                'verbose_name_plural': '玩家艾瑟萌属性加成',
            },
        ),
        migrations.CreateModel(
            name='PlayerExerParamBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='属性值')),
                ('expires_time', models.DateTimeField(null=True, verbose_name='过期时间')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.BaseParam', verbose_name='属性类型')),
                ('player_exer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.PlayerExermon', verbose_name='玩家艾瑟萌')),
            ],
            options={
                'verbose_name': '玩家艾瑟萌附加属性值',
                'verbose_name_plural': '玩家艾瑟萌附加属性值',
            },
        ),
    ]
