# Generated by Django 2.2.6 on 2020-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0009_auto_20200506_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='exeritem',
            name='batch_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='使用个数'),
        ),
    ]
