# Generated by Django 2.2.6 on 2020-05-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0010_exeritem_batch_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerequipprice',
            name='bound_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='绑定点券'),
        ),
        migrations.AlterField(
            model_name='exeritemprice',
            name='bound_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='绑定点券'),
        ),
    ]
