# Generated by Django 2.2.6 on 2020-07-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exermon_module', '0011_auto_20200509_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerequip',
            options={'verbose_name': '可装备物品', 'verbose_name_plural': '可装备物品'},
        ),
        migrations.AlterModelOptions(
            name='exerequipslot',
            options={'verbose_name': '槽类容器', 'verbose_name_plural': '槽类容器'},
        ),
        migrations.AlterModelOptions(
            name='exerequipslotitem',
            options={'verbose_name': '槽类容器项', 'verbose_name_plural': '槽类容器项'},
        ),
        migrations.AlterModelOptions(
            name='exerfrag',
            options={'verbose_name': '基础物品', 'verbose_name_plural': '基础物品'},
        ),
        migrations.AlterModelOptions(
            name='exerfragpack',
            options={'verbose_name': '背包类容器', 'verbose_name_plural': '背包类容器'},
        ),
        migrations.AlterModelOptions(
            name='exerfragpackitem',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.AlterModelOptions(
            name='exergift',
            options={'verbose_name': '基础物品', 'verbose_name_plural': '基础物品'},
        ),
        migrations.AlterModelOptions(
            name='exergiftpool',
            options={'verbose_name': '背包类容器', 'verbose_name_plural': '背包类容器'},
        ),
        migrations.AlterModelOptions(
            name='exerhub',
            options={'verbose_name': '背包类容器', 'verbose_name_plural': '背包类容器'},
        ),
        migrations.AlterModelOptions(
            name='exeritem',
            options={'verbose_name': '可用物品', 'verbose_name_plural': '可用物品'},
        ),
        migrations.AlterModelOptions(
            name='exermon',
            options={'verbose_name': '基础物品', 'verbose_name_plural': '基础物品'},
        ),
        migrations.AlterModelOptions(
            name='exerpack',
            options={'verbose_name': '背包类容器', 'verbose_name_plural': '背包类容器'},
        ),
        migrations.AlterModelOptions(
            name='exerpackequip',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.AlterModelOptions(
            name='exerpackitem',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.AlterModelOptions(
            name='exerskill',
            options={'verbose_name': '基础物品', 'verbose_name_plural': '基础物品'},
        ),
        migrations.AlterModelOptions(
            name='exerskillslot',
            options={'verbose_name': '槽类容器', 'verbose_name_plural': '槽类容器'},
        ),
        migrations.AlterModelOptions(
            name='exerskillslotitem',
            options={'verbose_name': '槽类容器项', 'verbose_name_plural': '槽类容器项'},
        ),
        migrations.AlterModelOptions(
            name='exerslot',
            options={'verbose_name': '槽类容器', 'verbose_name_plural': '槽类容器'},
        ),
        migrations.AlterModelOptions(
            name='exerslotitem',
            options={'verbose_name': '槽类容器项', 'verbose_name_plural': '槽类容器项'},
        ),
        migrations.AlterModelOptions(
            name='playerexergift',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.AlterModelOptions(
            name='playerexermon',
            options={'verbose_name': '背包类容器项', 'verbose_name_plural': '背包类容器项'},
        ),
        migrations.RenameField(
            model_name='exerequipslot',
            old_name='exer_slot',
            new_name='exer_slot_item',
        ),
        migrations.RemoveField(
            model_name='exermon',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='exermon',
            name='full',
        ),
        migrations.RemoveField(
            model_name='exermon',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='exerskill',
            name='ani',
        ),
        migrations.RemoveField(
            model_name='exerskill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='exerskill',
            name='target_ani',
        ),
        migrations.AlterField(
            model_name='exerequipslotitem',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerEquipSlot', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='exerequipslotitem',
            name='pack_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exermon_module.EquipPackItem', verbose_name='艾瑟萌背包装备'),
        ),
        migrations.AlterField(
            model_name='exerfragpackitem',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerFragPack', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='exerfragpackitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerFrag', verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='exerpackequip',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.EquipPack', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='exerpackequip',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.GameEquip', verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='exerpackitem',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.EquipPack', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='exerpackitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerItem', verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='exerskillslotitem',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSkillSlot', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='exerslotitem',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerSlot', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='exerslotitem',
            name='player_exer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exermon_module.PlayerExermon', verbose_name='玩家艾瑟萌'),
        ),
        migrations.AlterField(
            model_name='exerslotitem',
            name='player_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exermon_module.PlayerExerGift', verbose_name='玩家艾瑟萌天赋'),
        ),
        migrations.AlterField(
            model_name='playerexergift',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerGiftPool', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='playerexergift',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerGift', verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='playerexermon',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.ExerHub', verbose_name='容器'),
        ),
        migrations.AlterField(
            model_name='playerexermon',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exermon_module.Exermon', verbose_name='物品'),
        ),
    ]
