# Generated by Django 2.2.6 on 2020-08-22 00:08

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.cache_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season_module', '0002_comprank_compseason_seasonrecord_suspensionrecord'),
        ('question_module', '0002_correctingquestion_generalqueschoice_generalquespicture_generalquesrecord_generalquesreport_generalq'),
        ('game_module', '0002_auto_20200822_0008'),
        ('player_module', '0002_auto_20200822_0008'),
        ('record_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExerciseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('exer_exp_incrs', jsonfield.fields.JSONField(default={}, null=True, verbose_name='经验增加')),
                ('slot_exp_incrs', jsonfield.fields.JSONField(default={}, null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('finished', models.BooleanField(default=False, verbose_name='完成标志')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='题量')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season_module.CompSeason', verbose_name='所属赛季')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_module.Subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '题目集记录',
                'verbose_name_plural': '题目集记录',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='ElementPlayerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False, verbose_name='作答标志')),
                ('timespan', models.PositiveIntegerField(default=0, verbose_name='用时')),
                ('exp_incr', models.SmallIntegerField(null=True, verbose_name='经验增加')),
                ('slot_exp_incr', models.SmallIntegerField(null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('is_new', models.BooleanField(default=False, verbose_name='新题标志')),
                ('answer', models.CharField(blank=True, max_length=64, null=True, verbose_name='回答')),
                ('choices', jsonfield.fields.JSONField(default=[], verbose_name='选项')),
            ],
            options={
                'verbose_name': '基本玩家题目关系',
                'verbose_name_plural': '基本玩家题目关系',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='PhraseExerciseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('exer_exp_incrs', jsonfield.fields.JSONField(default={}, null=True, verbose_name='经验增加')),
                ('slot_exp_incrs', jsonfield.fields.JSONField(default={}, null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('finished', models.BooleanField(default=False, verbose_name='完成标志')),
                ('count', models.PositiveSmallIntegerField(default=10, verbose_name='题量')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '题目集记录',
                'verbose_name_plural': '题目集记录',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='WordExerciseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('exer_exp_incrs', jsonfield.fields.JSONField(default={}, null=True, verbose_name='经验增加')),
                ('slot_exp_incrs', jsonfield.fields.JSONField(default={}, null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('finished', models.BooleanField(default=False, verbose_name='完成标志')),
                ('count', models.PositiveSmallIntegerField(default=50, verbose_name='题量')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_module.Player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '题目集记录',
                'verbose_name_plural': '题目集记录',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='CollectingExerciseRecord',
            fields=[
                ('baseexerciserecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record_module.BaseExerciseRecord')),
            ],
            options={
                'verbose_name': '题目集记录',
                'verbose_name_plural': '题目集记录',
                'abstract': False,
            },
            bases=('record_module.baseexerciserecord',),
        ),
        migrations.CreateModel(
            name='GeneralExerciseRecord',
            fields=[
                ('baseexerciserecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record_module.BaseExerciseRecord')),
                ('gen_type', models.PositiveSmallIntegerField(choices=[(0, '普通模式'), (1, '已做优先'), (2, '未做优先'), (3, '错题优先'), (4, '收藏优先'), (5, '简单题优先'), (6, '中等题优先'), (7, '难题优先')], default=0, verbose_name='生成模式')),
            ],
            options={
                'verbose_name': '题目集记录',
                'verbose_name_plural': '题目集记录',
                'abstract': False,
            },
            bases=('record_module.baseexerciserecord',),
        ),
        migrations.CreateModel(
            name='ListeningExerciseRecord',
            fields=[
                ('baseexerciserecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record_module.BaseExerciseRecord')),
            ],
            options={
                'verbose_name': '题目集记录',
                'verbose_name_plural': '题目集记录',
                'abstract': False,
            },
            bases=('record_module.baseexerciserecord',),
        ),
        migrations.CreateModel(
            name='ReadingExerciseRecord',
            fields=[
                ('baseexerciserecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record_module.BaseExerciseRecord')),
            ],
            options={
                'verbose_name': '题目集记录',
                'verbose_name_plural': '题目集记录',
                'abstract': False,
            },
            bases=('record_module.baseexerciserecord',),
        ),
        migrations.CreateModel(
            name='WordExerciseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知物品'), (1, '游戏道具'), (2, '游戏装备'), (11, '游戏卡牌'), (101, '艾瑟萌'), (102, '艾瑟萌天赋'), (103, '艾瑟萌碎片'), (104, '艾瑟萌技能'), (201, '战斗敌人'), (202, '战斗状态'), (301, '特训物品'), (302, '特训药水'), (303, '特训卡片'), (310, '特训敌人'), (311, '特训状态')], verbose_name='物品类型')),
                ('item_id', models.PositiveSmallIntegerField(verbose_name='物品ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.WordExerciseRecord', verbose_name='单词题记录')),
            ],
            options={
                'verbose_name': '题目集奖励',
                'verbose_name_plural': '题目集奖励',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhraseExerciseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知物品'), (1, '游戏道具'), (2, '游戏装备'), (11, '游戏卡牌'), (101, '艾瑟萌'), (102, '艾瑟萌天赋'), (103, '艾瑟萌碎片'), (104, '艾瑟萌技能'), (201, '战斗敌人'), (202, '战斗状态'), (301, '特训物品'), (302, '特训药水'), (303, '特训卡片'), (310, '特训敌人'), (311, '特训状态')], verbose_name='物品类型')),
                ('item_id', models.PositiveSmallIntegerField(verbose_name='物品ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.PhraseExerciseRecord', verbose_name='短语题记录')),
            ],
            options={
                'verbose_name': '题目集奖励',
                'verbose_name_plural': '题目集奖励',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordExerciseQuestion',
            fields=[
                ('elementplayerquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record_module.ElementPlayerQuestion')),
                ('dictation', models.BooleanField(default=False, verbose_name='默写')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Word', verbose_name='题目')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.WordExerciseRecord', verbose_name='单词题记录')),
            ],
            options={
                'verbose_name': '基本玩家题目关系',
                'verbose_name_plural': '基本玩家题目关系',
                'abstract': False,
            },
            bases=('record_module.elementplayerquestion',),
        ),
        migrations.CreateModel(
            name='ReadingExerciseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知物品'), (1, '游戏道具'), (2, '游戏装备'), (11, '游戏卡牌'), (101, '艾瑟萌'), (102, '艾瑟萌天赋'), (103, '艾瑟萌碎片'), (104, '艾瑟萌技能'), (201, '战斗敌人'), (202, '战斗状态'), (301, '特训物品'), (302, '特训药水'), (303, '特训卡片'), (310, '特训敌人'), (311, '特训状态')], verbose_name='物品类型')),
                ('item_id', models.PositiveSmallIntegerField(verbose_name='物品ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.ReadingExerciseRecord', verbose_name='阅读题记录')),
            ],
            options={
                'verbose_name': '题目集奖励',
                'verbose_name_plural': '题目集奖励',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingExerciseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False, verbose_name='作答标志')),
                ('timespan', models.PositiveIntegerField(default=0, verbose_name='用时')),
                ('exp_incr', models.SmallIntegerField(null=True, verbose_name='经验增加')),
                ('slot_exp_incr', models.SmallIntegerField(null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('is_new', models.BooleanField(default=False, verbose_name='新题标志')),
                ('answers', jsonfield.fields.JSONField(default=[], verbose_name='回答情况')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.ReadingQuestion', verbose_name='题目')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.ReadingExerciseRecord', verbose_name='阅读题记录')),
            ],
            options={
                'verbose_name': '选择组合题目关系',
                'verbose_name_plural': '选择组合题目关系',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='PhraseExerciseQuestion',
            fields=[
                ('elementplayerquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='record_module.ElementPlayerQuestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.Phrase', verbose_name='题目')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.PhraseExerciseRecord', verbose_name='短语题记录')),
            ],
            options={
                'verbose_name': '基本玩家题目关系',
                'verbose_name_plural': '基本玩家题目关系',
                'abstract': False,
            },
            bases=('record_module.elementplayerquestion',),
        ),
        migrations.CreateModel(
            name='ListeningExerciseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知物品'), (1, '游戏道具'), (2, '游戏装备'), (11, '游戏卡牌'), (101, '艾瑟萌'), (102, '艾瑟萌天赋'), (103, '艾瑟萌碎片'), (104, '艾瑟萌技能'), (201, '战斗敌人'), (202, '战斗状态'), (301, '特训物品'), (302, '特训药水'), (303, '特训卡片'), (310, '特训敌人'), (311, '特训状态')], verbose_name='物品类型')),
                ('item_id', models.PositiveSmallIntegerField(verbose_name='物品ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.ListeningExerciseRecord', verbose_name='听力题记录')),
            ],
            options={
                'verbose_name': '题目集奖励',
                'verbose_name_plural': '题目集奖励',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListeningExerciseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False, verbose_name='作答标志')),
                ('timespan', models.PositiveIntegerField(default=0, verbose_name='用时')),
                ('exp_incr', models.SmallIntegerField(null=True, verbose_name='经验增加')),
                ('slot_exp_incr', models.SmallIntegerField(null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('is_new', models.BooleanField(default=False, verbose_name='新题标志')),
                ('answers', jsonfield.fields.JSONField(default=[], verbose_name='回答情况')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.ListeningQuestion', verbose_name='题目')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.ListeningExerciseRecord', verbose_name='听力题记录')),
            ],
            options={
                'verbose_name': '选择组合题目关系',
                'verbose_name_plural': '选择组合题目关系',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='GeneralExerciseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False, verbose_name='作答标志')),
                ('timespan', models.PositiveIntegerField(default=0, verbose_name='用时')),
                ('exp_incr', models.SmallIntegerField(null=True, verbose_name='经验增加')),
                ('slot_exp_incr', models.SmallIntegerField(null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('is_new', models.BooleanField(default=False, verbose_name='新题标志')),
                ('selection', jsonfield.fields.JSONField(default=[], verbose_name='选择情况')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.GeneralQuestion', verbose_name='题目')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.GeneralExerciseRecord', verbose_name='刷题记录')),
            ],
            options={
                'verbose_name': '选择题目关系',
                'verbose_name_plural': '选择题目关系',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='ExerciseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知物品'), (1, '游戏道具'), (2, '游戏装备'), (11, '游戏卡牌'), (101, '艾瑟萌'), (102, '艾瑟萌天赋'), (103, '艾瑟萌碎片'), (104, '艾瑟萌技能'), (201, '战斗敌人'), (202, '战斗状态'), (301, '特训物品'), (302, '特训药水'), (303, '特训卡片'), (310, '特训敌人'), (311, '特训状态')], verbose_name='物品类型')),
                ('item_id', models.PositiveSmallIntegerField(verbose_name='物品ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.GeneralExerciseRecord', verbose_name='刷题记录')),
            ],
            options={
                'verbose_name': '题目集奖励',
                'verbose_name_plural': '题目集奖励',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorrectingExerciseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False, verbose_name='作答标志')),
                ('timespan', models.PositiveIntegerField(default=0, verbose_name='用时')),
                ('exp_incr', models.SmallIntegerField(null=True, verbose_name='经验增加')),
                ('slot_exp_incr', models.SmallIntegerField(null=True, verbose_name='槽经验增加')),
                ('gold_incr', models.SmallIntegerField(null=True, verbose_name='金币增加')),
                ('is_new', models.BooleanField(default=False, verbose_name='新题标志')),
                ('wrong_items', jsonfield.fields.JSONField(default=[], verbose_name='回答错误项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_module.CorrectingQuestion', verbose_name='题目')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.CollectingExerciseRecord', verbose_name='改错题记录')),
            ],
            options={
                'verbose_name': '基本玩家题目关系',
                'verbose_name_plural': '基本玩家题目关系',
                'abstract': False,
            },
            bases=(models.Model, utils.cache_utils.CacheableObject),
        ),
        migrations.CreateModel(
            name='CollectingExerciseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '未知物品'), (1, '游戏道具'), (2, '游戏装备'), (11, '游戏卡牌'), (101, '艾瑟萌'), (102, '艾瑟萌天赋'), (103, '艾瑟萌碎片'), (104, '艾瑟萌技能'), (201, '战斗敌人'), (202, '战斗状态'), (301, '特训物品'), (302, '特训药水'), (303, '特训卡片'), (310, '特训敌人'), (311, '特训状态')], verbose_name='物品类型')),
                ('item_id', models.PositiveSmallIntegerField(verbose_name='物品ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.CollectingExerciseRecord', verbose_name='改错题记录')),
            ],
            options={
                'verbose_name': '题目集奖励',
                'verbose_name_plural': '题目集奖励',
                'abstract': False,
            },
        ),
    ]
