# Generated by Django 2.2.6 on 2020-04-21 13:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('record_module', '0002_exercisequestion_exerciserecord_exercisereward_questionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciserecord',
            name='exp_incr',
        ),
        migrations.RemoveField(
            model_name='exerciserecord',
            name='slot_exp_incr',
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='exer_exp_incrs',
            field=jsonfield.fields.JSONField(default={}, null=True, verbose_name='经验增加'),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='slot_exp_incrs',
            field=jsonfield.fields.JSONField(default={}, null=True, verbose_name='槽经验增加'),
        ),
    ]
