# Generated by Django 2.2.6 on 2020-02-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_module', '0002_exercisequestion_exerciserecord_questionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_module.ExerciseRecord', verbose_name='刷题记录')),
            ],
            options={
                'verbose_name': '刷题奖励',
                'verbose_name_plural': '刷题奖励',
            },
        ),
    ]
